CREATE TABLE T_MQREQUEST 
   (	
    ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
	C_VERSION INT, 
	C_ACTIVE BIT(1), 
	C_MANUALID VARCHAR(255), 
	C_ENABLE BIT(1), 
	C_KEY VARCHAR(255), 
	C_SEQUENCECODE VARCHAR(255), 
	C_MESSAGEBODY BIGINT(20) NOT NULL, 
	C_STATUS BIGINT(20) NOT NULL, 
	C_DATETIME VARCHAR(255), 
    primary key (ID)
    );
    
create index MQREQUEST_DATETIME_IDX on T_MQREQUEST (C_DATETIME);
create index MQREQUEST_SEQUENCECODE_IDX on T_MQREQUEST (C_SEQUENCECODE);
create index MQREQUEST_BLOBCONTAINER_IDX on T_MQREQUEST (C_MESSAGEBODY);
create index MQREQUEST_CATEGORYLEMENT_IDX on T_MQREQUEST (C_STATUS);

############################################################
CREATE TABLE T_MQBLOBCONTAINER 
   (	ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
	C_VERSION INT, 
	C_ACTIVE BIT(1), 
	C_BLOB BLOB, 
	C_CREATIONDATE VARCHAR(256), 
	C_MANUALID VARCHAR(255), 
	C_ENABLE BIT(1),
	primary key (ID)
   );
