CREATE TABLE T_SIMAREQUEST
  (
    ID                        BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION               INT,
    C_ACTIVE                BIT(1),
    C_ENABLE                BIT(1),
    C_MANUALID              VARCHAR(255),
    C_CREATIONDATETIME      VARCHAR(255),
    C_LASTMODIFIEDDATETIME  VARCHAR(255),
    c_machineIP             VARCHAR(255),
    c_userCode              VARCHAR(255),
    c_branchCode            VARCHAR(255),
    c_userFirstName         VARCHAR(255),
    c_userLastName          VARCHAR(255),
    C_STATUS                  BIGINT(20),
    C_serviceType             BIGINT(20),
    c_sendDate              VARCHAR(10),
    c_simaResponse            BIGINT(20),
    C_JMSREQUEST              BIGINT(20),
    PRIMARY KEY (ID)
);

CREATE TABLE T_SIMACUSTOMERREQUEST
  (
    ID               BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_SIMACUSTOMER   BIGINT(20),
    PRIMARY KEY (ID)
  );

CREATE TABLE T_SIMACUSTOMER
  (
    ID                       BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION              INT,
    C_ACTIVE               BIT(1),
    C_ENABLE               BIT(1),
    C_MANUALID             VARCHAR(255),
    C_CREATIONDATETIME     VARCHAR(255),
    C_LASTMODIFIEDDATETIME VARCHAR(255),
    C_CUSTOMER               BIGINT(20),
    C_STATUS                 BIGINT(20),
    C_IDENTIFIER           VARCHAR(255),
    C_IDENTIFIERTYPE       BIGINT(20),
    C_LASTSIMARESPONSE           BIGINT(20),
    C_LASTSIMAREQUEST            BIGINT(20),
    PRIMARY KEY (ID)
  );

CREATE TABLE T_SIMARESPONSE
  (
    ID                        BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION               INT,
    C_ACTIVE                BIT(1),
    C_ENABLE                BIT(1),
    C_MANUALID              VARCHAR(255),
    C_CREATIONDATETIME      VARCHAR(255),
    C_LASTMODIFIEDDATETIME  VARCHAR(255),
    c_machineIP             VARCHAR(255),
    c_userCode              VARCHAR(255),
    c_branchCode            VARCHAR(255),
    c_userFirstName         VARCHAR(255),
    c_userLastName          VARCHAR(255),
    c_ackStatus               BIGINT(20) ,
    C_isProcessed           BIT(1),
    C_JMSREQUEST              BIGINT(20) ,
    C_SIMAREQUEST             BIGINT(20),
    PRIMARY KEY (ID)
);

CREATE TABLE t_SimaResponseError
  (
    ID               BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION      INT,
    C_ACTIVE       BIT(1),
    C_ENABLE       BIT(1),
    C_MANUALID     VARCHAR(255),
    C_CREATIONDATETIME      VARCHAR(255),
    C_LASTMODIFIEDDATETIME  VARCHAR(255),
    C_message      VARCHAR(255),
    c_code         VARCHAR(255),
    C_SIMARESPONSE   BIGINT(20),
    PRIMARY KEY (ID)
  );

  CREATE TABLE T_JMSREQUEST
(
     ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
     C_MESSAGEID VARCHAR(255),
     c_pureMessageId VARCHAR(255),
     C_CORRELATIONID VARCHAR(255),
    PRIMARY KEY (ID)
);

--*****************************************************************************************************************************
-- Responsible Name = ma.raeisi

CREATE TABLE T_SIMAERRORDETAILS
(
    ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MESSAGE VARCHAR(255),
	C_STACKTRACE VARCHAR(4000),
	C_IDENTIFIER VARCHAR(255),
    C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_ISBUSINESSEXCEPTION BIT(1),
	C_OPERATION   BIGINT(20),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE T_SIMABLOCKCUSTOMERREQUEST
(	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_IDENTIFIER VARCHAR(64),
	C_IDENTIFIERTYPE   BIGINT(20),
	C_BLOCKDESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE T_SIMACUSTOMERLOG
(	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_SIMARESPONSE   BIGINT(20),
	C_SIMAREQUEST   BIGINT(20),
	C_SIMACUSTOMER   BIGINT(20),
	C_OPERATION   BIGINT(20),
	C_PREVALUE VARCHAR(64),
	C_NEXTVALUE VARCHAR(64),
	C_CHANGEDFIELD   BIGINT(20),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE T_SIMAACCOUNTLOG
(	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_SIMARESPONSE   BIGINT(20),
	C_SIMAREQUEST   BIGINT(20),
	C_SIMAACCOUNT   BIGINT(20),
	C_OPERATION   BIGINT(20),
	C_PREVALUE VARCHAR(64),
	C_NEXTVALUE VARCHAR(64),
	C_CHANGEDFIELD   BIGINT(20),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE T_SIMABLOCKCUSTOMER
(	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
    C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_SIMACUSTOMER   BIGINT(20),
    C_BLOCKDESCRIPTION VARCHAR(255),
	C_OPERATION   BIGINT(20),
  	C_CREATIONDATETIME VARCHAR(255),
	C_LASTMODIFIEDDATETIME VARCHAR(255),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE T_SIMABLOCKACCOUNT
(	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
    C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
    C_AMOUNT NUMERIC(38,4),
    C_DESCRIPTION VARCHAR(255),
	C_SIMAACCOUNT   BIGINT(20),
	C_OPERATION   BIGINT(20),
  	C_CREATIONDATETIME VARCHAR(255),
	C_LASTMODIFIEDDATETIME VARCHAR(255),
    PRIMARY KEY (ID)
)  ;

*****************************************************************************************************************************
-- Responsible Name = h.sedigh

CREATE TABLE T_SIMAEXCHANGEREQUEST
   (
    ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION              INT,
    C_ACTIVE               BIT(1),
    C_ENABLE               BIT(1),
    C_MANUALID             VARCHAR(255),
	C_COUNT NUMERIC(38,4),
	C_DESCRIPTION VARCHAR(255),
	C_SECURITIESCODE VARCHAR(255),
	C_SIMACUSTOMER   BIGINT(20),
    PRIMARY KEY (ID)
 );

CREATE TABLE t_SimaSecurities
  (
    ID                           BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION                  INT,
    C_ACTIVE                   BIT(1),
    C_ENABLE                   BIT(1),
    C_MANUALID                 VARCHAR(255),
    C_CREATIONDATETIME         VARCHAR(255),
    C_LASTMODIFIEDDATETIME     VARCHAR(255),
    c_code                     VARCHAR(255),
    c_name                     VARCHAR(255),
    c_groupCode                VARCHAR(255),
    c_interestIban             VARCHAR(64),
    c_principalIban            VARCHAR(64),
    c_groupDescription         VARCHAR(255),
    c_saleAvailableBalance     NUMERIC (38, 4),
    c_resaleAvailableBalPab    NUMERIC (38, 4),
    c_resaleAvailableBalAgn    NUMERIC (38, 4),
    c_status                     BIGINT(20),
    c_interestAmount           NUMERIC (38, 4),
    c_salable                  BIT(1),
    c_resalableByAgent         BIT(1),
    c_resalableByPublisher     BIT(1),
    c_redeemable               BIT(1),
    c_transferable             BIT(1),
    c_lastSimaResponse           BIGINT(20),
    c_lastSimaRequest            BIGINT(20),
    c_sellingStartDateFeature  VARCHAR(64),
    c_sellingEndDateFeature    VARCHAR(64),
    c_countFeature               BIGINT(20),
    c_finalRateOfReturnFeature NUMERIC (38, 4),
    c_parValueFeature          NUMERIC (38, 4),
    c_redemptionRateFeature    NUMERIC (38, 4),
    c_couponRateFeature        NUMERIC (38, 4),
    c_interestPayIntervalFeatu NUMERIC (19, 0),
    c_couponsDate              NUMERIC (19, 0),
    c_features                 NUMERIC (19, 0),
    C_interestPaymentIntervalU   BIGINT(20),
    C_isLast                   BIT(1),
    C_dailyInterestAmount      NUMERIC(38,6),
    C_ISSPECIAL BIT(1),
    C_DEPOSITID   BIGINT(20),
    C_DEBTORTOPICID   BIGINT(20),
    C_CREDITORTOPICID   BIGINT(20),
    PRIMARY KEY (ID)
  );

CREATE TABLE t_SimaSecuritiesLog
  (
    ID                  BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION         INT,
    C_ACTIVE          BIT(1),
    C_ENABLE          BIT(1),
    C_MANUALID        VARCHAR(255),
    C_PREVALUE        VARCHAR(64),
    C_NEXTVALUE       VARCHAR(64),
    C_CHANGEDFIELD      BIGINT(20),
    C_OPERATION         BIGINT(20) ,
    C_SIMARESPONSE      BIGINT(20) ,
    C_SIMAREQUEST       BIGINT(20) ,
    C_SIMASECURITIES    BIGINT(20),
    C_MACHINEIP       VARCHAR(255),
    C_USERCODE        VARCHAR(255),
    C_BRANCHCODE      VARCHAR(255),
    C_DESCRIPTION     VARCHAR(255),
    C_TRANSACTIONCODE VARCHAR(255),
    C_DATE            VARCHAR(255),
    C_TIME            VARCHAR(255),
    C_USERFIRSTNAME   VARCHAR(255),
    C_USERLASTNAME    VARCHAR(255),
    PRIMARY KEY (ID)
  );

CREATE TABLE T_SIMAACCOUNT
(
    ID                           BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION                  INT,
    C_ACTIVE                   BIT(1),
    C_ENABLE                   BIT(1),
    C_MANUALID                 VARCHAR(255),
    C_CREATIONDATETIME         VARCHAR(255),
    C_LASTMODIFIEDDATETIME     VARCHAR(255),
	C_ACCOUNTNUMERIC            VARCHAR(255),
	C_TOTALBALANCE               BIGINT(20),
	C_BLOCKBALANCE               BIGINT(20),
	C_AVAILABLEBALANCE           BIGINT(20),
	C_STATUS                     BIGINT(20),
    c_creditorAccountId          BIGINT(20),
    C_LASTSIMARESPONSE           BIGINT(20),
	C_LASTSIMAREQUEST            BIGINT(20),
    PRIMARY KEY (ID)
);

CREATE TABLE t_SimaContract
  (
    ID                           BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION                  INT,
    C_ACTIVE                   BIT(1),
    C_ENABLE                   BIT(1),
    C_MANUALID                 VARCHAR(255),
    C_CREATIONDATETIME         VARCHAR(255),
    C_LASTMODIFIEDDATETIME     VARCHAR(255),
    C_SIMACUSTOMER               BIGINT(20),
    C_SIMASECURITIES             BIGINT(20),
    C_SIMAACCOUNT                BIGINT(20),
    C_ACTION                     BIGINT(20),
    c_lastSimaResponse           BIGINT(20),
    C_COUNT                      BIGINT(20),
    C_DESCRIPTION              VARCHAR(2000),
    C_TRANSACTIONNUMERIC        VARCHAR(255),
    C_PAIDAMOUNT               NUMERIC(38,4),
    C_DUEDATE                  VARCHAR(10),
    C_STATUS                     BIGINT(20),
    C_redemptionPenaltyAmou    NUMERIC(38,4),
    C_resaleInterest           NUMERIC(38,4),
    C_redemptionInterest       NUMERIC(38,4),
    c_iban                     VARCHAR(255),
    c_lastSimaRequest            BIGINT(20),
    C_CONTRACTFORM             NUMERIC(19, 0),
    C_SIMATRANSACTIONID        VARCHAR(255),
    C_BRANCHCODE               VARCHAR(255),
    C_REVERSETRANSACTIONNUM    VARCHAR(255),
    PRIMARY KEY (ID)
  );
  **********************************************************************************************************************
CREATE TABLE t_SimaContractLog
  (
    ID                  BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION         INT,
    C_ACTIVE          BIT(1),
    C_ENABLE          BIT(1),
    C_MANUALID        VARCHAR(255),
    C_PREVALUE        VARCHAR(64),
    C_NEXTVALUE       VARCHAR(64),
    C_CHANGEDFIELD      BIGINT(20),
    C_OPERATION         BIGINT(20) ,
    C_SIMARESPONSE      BIGINT(20) ,
    C_SIMAREQUEST       BIGINT(20) ,
    C_SIMACONTRACT     BIGINT(20),
    C_MACHINEIP       VARCHAR(255),
    C_USERCODE        VARCHAR(255),
    C_BRANCHCODE      VARCHAR(255),
    C_DESCRIPTION     VARCHAR(255),
    C_TRANSACTIONCODE VARCHAR(255),
    C_DATE            VARCHAR(255),
    C_TIME            VARCHAR(255),
    C_USERFIRSTNAME   VARCHAR(255),
    C_USERLASTNAME    VARCHAR(255),
    PRIMARY KEY (ID)
  );
************************************************************************************************************************
CREATE TABLE t_SimaRedBranchDetail (
    ID                           BIGINT(20) NOT NULL AUTO_INCREMENT,
    C_VERSION                  INT,
    C_ACTIVE                   BIT(1),
    C_ENABLE                   BIT(1),
    C_MANUALID                 VARCHAR(255),
    C_CREATIONDATETIME         VARCHAR(255),
    C_LASTMODIFIEDDATETIME     VARCHAR(255),
    c_branchCode               VARCHAR(64),
    c_interestAmount           NUMERIC (38, 4),
    c_penaltyAmount            NUMERIC (38, 4),
    c_SimaRedemptionContrac     BIGINT(20),
    PRIMARY KEY (ID)
);

CREATE TABLE t_SimaRedemptionContrac (
    ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
    c_parentContract                  BIGINT(20),
    c_tradingSource     VARCHAR(64),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE t_SimaResaleContract (
    ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
    c_parentContract         BIGINT(20),
    c_interestAmount       NUMERIC (38, 4),
    c_tradingSource          BIGINT(20),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE t_SimaSaleContract (
    ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
    c_interestAmount       NUMERIC (38, 4),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE t_SimaTransferContract (
    ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
    c_parentContract     BIGINT(20),
    PRIMARY KEY (ID)
)  ;

CREATE TABLE t_SimaAccount (
ID                           BIGINT(20) NOT NULL AUTO_INCREMENT,
C_VERSION                  INT,
C_ACTIVE                   BIT(1),
C_ENABLE                   BIT(1),
C_MANUALID                 VARCHAR(255),
C_CREATIONDATETIME         VARCHAR(255),
C_LASTMODIFIEDDATETIME     VARCHAR(255),
c_accountNUMERIC             VARCHAR(255),
c_availableBalance            BIGINT(20),
c_blockBalance                BIGINT(20),
c_totalBalance                BIGINT(20),
c_status                      BIGINT(20),
c_lastSimaResponse            BIGINT(20),
c_lastSimaRequest             BIGINT(20),
C_SIMATRANSACTIONID         VARCHAR(255),
    PRIMARY KEY (ID)
)  ;

  CREATE TABLE T_DAILYREVERSEREPORTLOG
   (
   ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_STATUS   BIGINT(20),
	C_FILEUNIQUEIDENTIFIER VARCHAR(255),
	C_SIMAREQUEST   BIGINT(20),
	C_MAINTRANSACTIONID VARCHAR(255),
	C_MAINTRANSACTIONOPERATION   BIGINT(20),
	C_REVERSEDATE VARCHAR(64),
	C_REVERSEBRANCHINDEX VARCHAR(255),
	C_REVERSEBRANCHNAME VARCHAR(255),
	C_MESSAGEID VARCHAR(255),
    PRIMARY KEY (ID)
	 )  ;

CREATE TABLE T_DAILYREDEMPTIONREPORTLOG
   (
   	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_STATUS   BIGINT(20),
	C_FILEUNIQUEIDENTIFIER VARCHAR(255),
	C_TRANSACTIONID VARCHAR(255),
	C_TRANSACTIONDATE VARCHAR(255),
	C_BRANCHINDEX VARCHAR(255),
	C_BRANCHNAME VARCHAR(255),
    C_SECURITIESCODE VARCHAR(255),
	C_ACCOUNTNUMERIC VARCHAR(255),
	C_OWNERIDENTIFIERTYPE   BIGINT(20),
	C_OWNERIDENTIFIER VARCHAR(255),
	C_TRADINGSOURCETYPE   BIGINT(20),
	C_TRANSACTIONDESCRIPTION VARCHAR(255),
    C_TRANSACTIONAMOUNT NUMERIC(38,4),
    C_TRANSACTIONINTERESTAMOUN NUMERIC(38,4),
    C_TRANSACTIONPENALTYAMOUNT NUMERIC(38,4),
	C_MESSAGEID VARCHAR(255),
    PRIMARY KEY (ID)
	 )  ;

    CREATE TABLE T_DAILYSALEREPORTLOG
   (
   	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_STATUS   BIGINT(20),
	C_FILEUNIQUEIDENTIFIER VARCHAR(255),
	C_TRANSACTIONID VARCHAR(255),
	C_TRANSACTIONDATE VARCHAR(255),
	C_BRANCHINDEX VARCHAR(255),
	C_BRANCHNAME VARCHAR(255),
    C_SECURITIESCODE VARCHAR(255),
    C_ACCOUNTNUMERIC VARCHAR(255),
	C_OWNERIDENTIFIERTYPE   BIGINT(20),
	C_OWNERIDENTIFIER VARCHAR(255),
	C_TRANSACTIONDESCRIPTION VARCHAR(255),
    C_TRANSACTIONAMOUNT NUMERIC(38,4),
    C_TRANSACTIONINTERESTAMOUN NUMERIC(38,4),
	C_MESSAGEID VARCHAR(255),
    PRIMARY KEY (ID)
	 )  ;

CREATE TABLE T_DAILYRESALEREPORTLOG
   (
   	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_STATUS   BIGINT(20),
	C_FILEUNIQUEIDENTIFIER VARCHAR(255),
	C_TRANSACTIONID VARCHAR(255),
	C_TRANSACTIONDATE VARCHAR(255),
	C_BRANCHINDEX VARCHAR(255),
	C_BRANCHNAME VARCHAR(255),
    C_SECURITIESCODE VARCHAR(255),
    C_ACCOUNTNUMERIC VARCHAR(255),
	C_OWNERIDENTIFIERTYPE   BIGINT(20),
	C_OWNERIDENTIFIER VARCHAR(255),
    C_TRADINGSOURCETYPE   BIGINT(20),
	C_TRANSACTIONDESCRIPTION VARCHAR(255),
    C_TRANSACTIONAMOUNT NUMERIC(38,4),
    C_TRANSACTIONINTERESTAMOUN   BIGINT(20),
	C_MESSAGEID VARCHAR(255),
    PRIMARY KEY (ID)
	 )  ;

	 CREATE TABLE T_DAILYTRANSFERREPORTLOG
   (
   	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_STATUS   BIGINT(20),
	C_FILEUNIQUEIDENTIFIER VARCHAR(255),
	C_TRANSACTIONID VARCHAR(255),
	C_TRANSACTIONDATE VARCHAR(255),
	C_BRANCHINDEX VARCHAR(255),
	C_BRANCHNAME VARCHAR(255),
    C_SECURITIESCODE VARCHAR(255),
    C_FROMACCOUNTNUMERIC VARCHAR(255),
	C_FROMIDENTIFIERTYPE   BIGINT(20),
	C_FROMIDENTIFIER VARCHAR(255),
	C_TOACCOUNTNUMERIC VARCHAR(255),
	C_TOIDENTIFIERTYPE   BIGINT(20),
	C_TOIDENTIFIER VARCHAR(255),
	C_TRANSACTIONDESCRIPTION VARCHAR(255),
    C_TRANSACTIONAMOUNT NUMERIC(38,4),
	C_MESSAGEID VARCHAR(255),
    PRIMARY KEY (ID)
	 )  ;

CREATE TABLE T_DAILYINTERESTREPORTLOG
   (	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_STATUS   BIGINT(20),
	C_FILEUNIQUEIDENTIFIER VARCHAR(255),
	C_INTERESTDATE VARCHAR(255),
	C_SECURITIESCODE VARCHAR(255),
    C_ACCOUNTNUMERIC VARCHAR(255),
	C_OWNERIDENTIFIERTYPE   BIGINT(20),
	C_OWNERIDENTIFIER VARCHAR(255),
    C_INTERESTAMOUNT NUMERIC(38,4),
    PRIMARY KEY (ID)
	 )  ;

	 CREATE TABLE T_DAILYBLOCKREPORTLOG
   (	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_STATUS   BIGINT(20),
	C_FILEUNIQUEIDENTIFIER VARCHAR(255),
	C_BLOCKDATE VARCHAR(255),
	C_BLOCKOPERATION   BIGINT(20),
	C_BRANCHINDEX VARCHAR(255),
	C_BRANCHNAME VARCHAR(255),
    C_SECURITIESCODE VARCHAR(255),
	C_ACCOUNTNUMERIC VARCHAR(255),
	C_OWNERIDENTIFIERTYPE   BIGINT(20),
	C_OWNERIDENTIFIER VARCHAR(255),
	C_TRANSACTIONDESCRIPTION VARCHAR(255),
    C_BLOCKAMOUNT NUMERIC(38,4),
    C_MESSAGEID VARCHAR(255),
    PRIMARY KEY (ID)
	 )  ;

	 CREATE TABLE T_SIMADEPOSITINTERESTLOG
   (	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_MACHINEIP VARCHAR(255),
	C_USERCODE VARCHAR(255),
	C_BRANCHCODE VARCHAR(255),
	C_DESCRIPTION VARCHAR(255),
	C_TRANSACTIONCODE VARCHAR(255),
	C_DATE VARCHAR(255),
	C_TIME VARCHAR(255),
	C_USERFIRSTNAME VARCHAR(255),
	C_USERLASTNAME VARCHAR(255),
	C_FILEUNIQUEIDENTIFIER VARCHAR(255),
	C_SECURITIESCODE VARCHAR(255),
	C_MESSAGEID VARCHAR(255),
	C_FILECREATIONDATETIME VARCHAR(255),
	C_NUMERICOFTRANSACTIONS   BIGINT(20),
	C_INTERESTAMOUNTSUM NUMERIC(38,4),
    C_DEBTORBANKNAME VARCHAR(255),
    C_DEBTORBANKIBAN VARCHAR(255),
    C_DEBTORBANKBIC VARCHAR(255),
    PRIMARY KEY (ID)
	 )  ;

CREATE TABLE T_INTERESTTRANSACTIONINFO
   (	ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
	C_VERSION INT,
	C_ACTIVE BIT(1),
	C_ENABLE BIT(1),
	C_MANUALID VARCHAR(255),
	C_CREATIONDATETIME      VARCHAR(255),
    C_LASTMODIFIEDDATETIME  VARCHAR(255),
	C_INTERESTAMOUNT NUMERIC(38,4),
	C_SIMACUSTOMERIDENTIFIER VARCHAR(255),
	C_CREDITORNAME VARCHAR(255),
	C_CREDITORIBAN VARCHAR(255),
    C_CREDITORACCOUNTNUMERIC VARCHAR(255),
    C_TRANSACTIONCODE VARCHAR(255),
    C_STATUS   BIGINT(20),
    C_MESSAGE VARCHAR(255),
    C_DEPOSITINTERESTLOG   BIGINT(20),
    PRIMARY KEY (ID)
	 )  ;

Create TABLE T_simaTaskItemLog (
ID                           BIGINT(20) NOT NULL AUTO_INCREMENT,
C_VERSION                  INT,
C_ACTIVE                   BIT(1),
C_ENABLE                   BIT(1),
C_MANUALID                 VARCHAR(255),
C_CREATIONDATETIME         VARCHAR(255),
C_LASTMODIFIEDDATETIME     VARCHAR(255),
c_taskItemId                 BIGINT(20),
    PRIMARY KEY (ID)
)  ;

Create TABLE T_SIMAISSUEDOCUMENTERROR (
ID                           BIGINT(20) NOT NULL AUTO_INCREMENT,
C_VERSION                  INT,
C_ACTIVE                   BIT(1),
C_ENABLE                   BIT(1),
C_MANUALID                 VARCHAR(255),
C_CREATIONDATETIME         VARCHAR(255),
C_LASTMODIFIEDDATETIME     VARCHAR(255),
C_SIMACONTRACT               BIGINT(20),
C_MESSAGE                  VARCHAR(255),
C_STACKTRACE               VARCHAR(4000),
    PRIMARY KEY (ID)
)  ;

create table T_SIMAFILEREPOSITORY (
ID                           BIGINT(20) NOT NULL AUTO_INCREMENT,
C_VERSION                  INT,
C_ACTIVE                   BIT(1),
C_ENABLE                   BIT(1),
C_MANUALID                 VARCHAR(255),
C_FILEUNIQUEIDENTIFIER     VARCHAR(255),
C_ISPROCESSED              BIT(1),
C_FILETYPE                 VARCHAR(255),
C_FILEBODY                   BIGINT(20),
C_INSERTIONDATE            VARCHAR(255),
C_INSERTIONTIME            VARCHAR(255),
C_REPORTTYPE               VARCHAR(255),
    PRIMARY KEY (ID)
  ) ;

ALTER TABLE T_SIMABLOCKACCOUNT   MODIFY  C_AMOUNT NUMERIC(38,4);
ALTER TABLE t_SimaSecurities   MODIFY  C_dailyInterestAmount NUMERIC(38,6);
ALTER TABLE T_DAILYREDEMPTIONREPORTLOG   MODIFY  C_TRANSACTIONAMOUNT NUMERIC(38,4);
ALTER TABLE T_DAILYREDEMPTIONREPORTLOG   MODIFY  C_TRANSACTIONINTERESTAMOUN NUMERIC(38,4);
ALTER TABLE T_DAILYREDEMPTIONREPORTLOG   MODIFY  C_TRANSACTIONPENALTYAMOUNT NUMERIC(38,4);
ALTER TABLE T_DAILYREDEMPTIONREPORTLOG   MODIFY  C_TRANSACTIONAMOUNT NUMERIC(38,4);
ALTER TABLE T_DAILYSALEREPORTLOG   MODIFY  C_TRANSACTIONAMOUNT NUMERIC(38,4);
ALTER TABLE T_DAILYSALEREPORTLOG   MODIFY  C_TRANSACTIONINTERESTAMOUN NUMERIC(38,4);
ALTER TABLE T_DAILYRESALEREPORTLOG   MODIFY  C_TRANSACTIONAMOUNT NUMERIC(38,4);
ALTER TABLE T_DAILYTRANSFERREPORTLOG   MODIFY  C_TRANSACTIONAMOUNT NUMERIC(38,4);
ALTER TABLE T_DAILYINTERESTREPORTLOG   MODIFY  C_INTERESTAMOUNT NUMERIC(38,4);
ALTER TABLE T_DAILYBLOCKREPORTLOG   MODIFY  C_BLOCKAMOUNT NUMERIC(38,4);
ALTER TABLE T_SIMADEPOSITINTERESTLOG   MODIFY  C_INTERESTAMOUNTSUM NUMERIC(38,4);
ALTER TABLE T_INTERESTTRANSACTIONINFO   MODIFY  C_INTERESTAMOUNT NUMERIC(38,4);


ALTER TABLE T_SIMAREQUEST ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMACUSTOMERREQUEST ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMACUSTOMER ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMARESPONSE ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaResponseError ADD PRIMARY KEY (ID);
ALTER TABLE T_JMSREQUEST ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMAERRORDETAILS ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMABLOCKCUSTOMERREQUEST ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMACUSTOMERLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMAACCOUNTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMABLOCKCUSTOMER ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMABLOCKACCOUNT ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMAEXCHANGEREQUEST ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaSecurities ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaSecuritiesLog ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMAACCOUNT ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaSecuritiesLog ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaContract ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaContractLog ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaRedBranchDetail ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaRedemptionContrac ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaResaleContract ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaSaleContract ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaTransferContract ADD PRIMARY KEY (ID);
ALTER TABLE t_SimaAccount ADD PRIMARY KEY (ID);
ALTER TABLE T_DAILYREVERSEREPORTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_DAILYREDEMPTIONREPORTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_DAILYSALEREPORTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_DAILYRESALEREPORTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_DAILYTRANSFERREPORTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_DAILYINTERESTREPORTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_DAILYBLOCKREPORTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMADEPOSITINTERESTLOG ADD PRIMARY KEY (ID);
ALTER TABLE T_INTERESTTRANSACTIONINFO ADD PRIMARY KEY (ID);
ALTER TABLE T_simaTaskItemLog ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMAISSUEDOCUMENTERROR ADD PRIMARY KEY (ID);
ALTER TABLE T_SIMAFILEREPOSITORY ADD PRIMARY KEY (ID);
-- creating index for simasearch
CREATE INDEX SIMA_SEC_LAST_CODE_IDX  ON T_SIMASECURITIES (C_ISLAST,C_CODE);
CREATE INDEX SIMA_SEC_LAST_STATUS_IDX  ON T_SIMASECURITIES (C_ISLAST,C_STATUS);
CREATE INDEX SIMA_SEC_LAST_ST_EN_IDX  ON T_SIMASECURITIES (C_ISLAST,C_SELLINGSTARTDATEFEATURE, C_SELLINGENDDATEFEATURE);
CREATE INDEX SIMA_CONT_TX_CUSTNO_IDX  ON T_SIMACONTRACT (C_SIMATRANSACTIONID,C_SIMACUSTOMER);
CREATE INDEX SIMA_CUSTOMER_CUSTNO_STATUS_IDX ON T_SIMACUSTOMER (C_CUSTOMER,C_STATUS);
CREATE INDEX SIMA_ACC_STATUS_IDX ON T_SIMAACCOUNT (C_STATUS);
CREATE INDEX SIMA_ACC_ACCNO_IDX ON T_SIMAACCOUNT (C_ACCOUNTNUMERIC);