package com.example.sima;

import java.math.BigDecimal;

public interface SharedCodes {

    int BOP_MAX_RESULT = 500;
    String DEBTOR = "DEBTOR";
    String CREDITOR = "CREDITOR";

    String IDENTIFIER_FOR_ALL_ENTITIES = "IDENTIFIER_FOR_ALL_ENTITIES";

    //topic underline or overline
    String OVERLINE = "OVERLINE";
    String UNDERLINE = "UNDERLINE";

    //account states
    String OPEN = "OPEN";
    String CLOSE = "CLOSE";
    String STAGNANT = "STAGNANT";
    String FORMERE = "FORMERE";
    String BLOCKED = "BLOCKED";
    String DEBTOR_BLOCKED = "DEBTOR_BLOCKED"; //equivalent to withdraw-blocked
    String CREDITOR_BLOCKED = "CREDITOR_BLOCKED";//equivalent to deopsit-blocked

    // relation types
    String RELATION_TYPES = "RELATION_TYPES";
    String UNUSED_RELATION_TYPES = "UNUSED_RELATION_TYPES";
    String ownerAndSignerRelationType = "depositOwnerAndSignerRelationType";
    String signerRelationType = "depositSignerRelationType";
    String introducerRelationType = "depositIntroducerRelationType";
    String ownerRelationType = "depositOwnerRelationType";
    String openerRelationType = "depositOpenerRelationType";
    String removedRelationType = "depositRemovedRelationType";
    String giftRelationType = "depositGiftRelationType";
    String covenantRelationType = "depositCovenantRelationType";
    String lawyerRelationType = "depositLawyerRelationType";
    String executorRelationType = "executorRelationType";
    String guardianRelationType = "guardianRelationType";
    String parentRelationType = "parentRelationType";
    String motherRelationType = "motherRelationType";

    //deposit states
    String openState = "openState";
    String closeState = "closeState";
    String blockState = "blockState";
    String withdrawBlockState = "withdrawBlockState";
    String depositBlockState = "depositBlockState";
    String partialAmountBlockState = "partialAmountBlockState";
    String wholeAmountBlockState = "wholeAmountBlockState";
    String stagnantState = "stagnantState";

    //deposit states in merge Project
    int mergeProjectOpenState = 0;
    int mergeProjectCloseState = 1;
    int mergeProjectDepositBlockState = 4;
    int mergeProjectWithdrawBlockState = 5;
    int mergeProjectBlockState = 6 ;
    int mergeProjectPartialAmountBlockState = 7;

    //retrictions
    String SAVE = "save";
    String UPDATE = "update";
    String DELETE = "delete";
    String LOAD = "load";
    String LESS_THAN = "lessThan";
    String GREATER_THAN = "greaterThan";

    String SYSTEM_BRANCH = "";// ManagementCodes.CENTRAL_BRANCH;

    //system
    String BRANCH = "branch";
    String SYSTEM_BANK = "SYSTEM_BANK";
    String AUTHORITY = "authority";
    String IP_ADDRESS = "ipAddress";
    String CENTRAL_BANK = "CENTRAL_BANK";
    String VIRTUAL_BRANCHES = "VIRTUAL_BRANCHES";
    String ESB_BRANCH = "ESB_BRANCH";
    String MODERN_BRANCH = "MODERN_BRANCH";
    String WEBSERVICE_BRANCH = "WEBSERVICE_BRANCH";
    String GAR_CENTRAL_BRANCH = "GAR_CENTRAL_BRANCH";
    String GAR_BRANCH1 = "GAR_BRANCH1";
    String GAR_BRANCH2 = "GAR_BRANCH2";
    String GAR_BRANCH3 = "GAR_BRANCH3";
    String RES_BAM_BRANCH = "RES_BAM_BRANCH";
    String ESB2_PERSONNEL_CODE = "ESB2_PERSONNEL_CODE";
    String POD_BRANCH = "POD_BRANCH";

    //document template
    String DOCUMENT_TEMPLATE_CODE = "DOCUMENT_TEMPLATE_CODE";
    String USECASE_DEFINED_TEMPLATE_VARIABLES = "USECASE_DEFINED_TEMPLATE_VARIABLES";
    String USECASE_DEFINED_COMMENT_VARIABLES = "USECASE_DEFINED_COMMMENT_VARIABLES";
    String DD_COMMENT = "DD_COMMENT";
    String IS_CAR_DESTINATION = "IS_CAR_DESTINATION";

    //minimum and maximum amount for displaying in the system
    BigDecimal MAX_AMOUNT = new BigDecimal("9999999999999999999999999999");
    BigDecimal MIN_AMOUNT = BigDecimal.ZERO;
    String COMMISSION_ACCOUNT = "COMMISSION_ACCOUNT";

    // withdraw tools
    String WITHDRAW_TOOL = "WITHDRAW_TOOL";
    String chequeTool = "chequeTool";
    String orderedPaymentTool = "orderedPaymentTool";
    String cardTool = "cardTool";
    String internalDocumentTool = "internalDocumentTool";
    String internetTool = "internetTool";
    String telephoneTool = "telephoneTool";

    // TRANSFER BOOK STATES
    String REGISTERED_BOOK = "REGISTERED_BOOK";
    String SENT_BOOK = "SENT_BOOK";
    String RECEIVED_BOOK = "RECEIVED_BOOK";
    String LOST_BOOK = "LOST_BOOK";
    String DELETED_BOOK = "DELETED_BOOK";

    // SENT BOOK TYPE
    String SENT_TO_CLEAR = "SENT_TO_CLEAR";
    String SENT_FROM_CLEAR = "SENT_FROM_CLEAR";
    String SENT_FROM_CLEAR_BOUNCED_CHEQUES = "SENT_FROM_CLEAR_BOUNCED_CHEQUES";
    String SENT_FROM_CLEAR_REJECTED_CHEQUES = "SENT_FROM_CLEAR_REJECTED_CHEQUES";

    //  TRANSFERABLE_PHYSICAL_STATE
    String REGISTERED_TRANSFERABLE = "REGISTERED_TRANSFERABLE";
    String SENT_TRANSFERABLE = "SENT_TRANSFERABLE";
    String RECEIVED_TRANSFERABLE = "RECEIVED_TRANSFERABLE";
    String LOST_TRANSFERABLE = "LOST_TRANSFERABLE";
    String CANCELLED_TRANSFERABLE = "CANCELLED_TRANSFERABLE";
    String RETURNED_TO_COSTUMER="RETURNED_TO_COSTUMER";
    String WAIT_FOR_INVALIDATE ="WAIT_FOR_INVALIDATE";

    // transferable types
    String TRANSFERABLE_TYPE_CATEGORY = "TRANSFERABLE_TYPE_CATEGORY";
    String partnershipDocumentTransferableType = "partnershipDocumentTransferableType";
    String commonChequeTransferableType = "commonChequeTransferableType";
    String issuableChequeTransferableType = "issuableChequeTransferableType";
    String certifiedChequeTransferableType = "certifiedChequeTransferableType";

    //libor period types
    String dailyLiborPeriodType = "dailyLiborPeriodType";
    String weeklyLiborPeriodType = "weeklyLiborPeriodType";
    String monthlyLiborPeriodType = "monthlyLiborPeriodType";
    String threeMonthLiborPeriodType = "threeMonthLiborPeriodType";
    String sixMonthLiborPeriodType = "sixMonthLiborPeriodType";
    String nineMonthLiborPeriodType = "nineMonthLiborPeriodType";
    String yearlyLiborPeriodType = "yearlyLiborPeriodType";
    String temporaryLiborPeriodType = "temporaryLiborPeriodType";

    // Sequence objects' keys
    String TRANSACTION_NUMBER = "TRANSACTION_NUMBER";
    String USECASE_RETURN_VO = "USECASE_RETURN_VO";

    int SCALE = 10;
    int PRECISION = 30;

    // Serial Type Code
    String LOAN_FILE_SERIAL = "LOAN_FILE_SERIAL";
    String LOAN_FILE_GROUP_SERIAL = "LOAN_FILE_GROUP_SERIAL";
    String DEPOSIT_SERIAL = "DEPOSIT_SERIAL";
    String SATNA_SERIAL = "SATNA_SERIAL";
    String PROOF_NUMBER = "PROOF_NUMBER";
    String NEW_PROOF_NUMBER = "NEW_PROOF_NUMBER";
    String CREDIT_SERIAL = "CREDIT_SERIAL";
    String NASHR2_SERIAL = "NASHR2_SERIAL";
    String ORDER_REG_SERIAL = "ORDER_REG_SERIAL";
    String FORM_SERIE = "FORM_SERIE";
    String BOP_SERIAL = "BOP_SERIAL";
    String CREDIT_DEPOSIT_SERIAL = "CREDIT_DEPOSIT_SERIAL";
    int CURRENCY_AMOUNT_SCALE = 2;
    int DEFAULT_CURRENCY_AMOUNT_SCALE = 0;

    String SCRIPT_TYPE = "SCRIPT_TYPE";
    String SCRIPT_STATUS = "SCRIPT_STATUS";

    String READY_SCRIPT = "READY_SCRIPT";
    String SUCCESSFUL_SCRIPT = "SUCCESSFUL_SCRIPT";
    String UNSUCCESSFUL_SCRIPT = "UNSUCCESSFUL_SCRIPT";
    String RUNNING_SCRIPT = "RUNNING_SCRIPT";
    String CANCELED_SCRIPT = "CANCELED_SCRIPT";

    String RIGHT_THUMB = "RIGHT_THUMB";
    String RIGHT_INDEX = "RIGHT_INDEX";
    String RIGHT_MIDDLE = "RIGHT_MIDDLE";
    String RIGHT_RING = "RIGHT_RING";
    String RIGHT_LITTLE = "RIGHT_LITTLE";
    String LEFT_THUMB = "LEFT_THUMB";
    String LEFT_INDEX = "LEFT_INDEX";
    String LEFT_MIDDLE = "LEFT_MIDDLE";
    String LEFT_RING = "LEFT_RING";
    String LEFT_LITTLE = "LEFT_LITTLE";

    String FINGERPRINT_MANDATORY = "FINGERPRINT_MANDATORY";
    String USING_FINGERPRINT = "USING_FINGERPRINT";
    String FINGERPRINT_MODIFICATION = "FINGERPRINT_MODIFICATION";

    //file for 28.1 status
    String REVOKE = "REVOKE";
    String SETTLE = "SETTLE";

    //loanfile Status
    String LOAN_REVOKED = "LOAN_REVOKED";

    //loanfile Operations
    String SETTLE_LOAN = "SETTLE_LOAN";
    String RECEIVE_LOAN_INSTALLMENT = "RECEIVE_LOAN_INSTALLMENT";
    String GRANT_LOAN = "GRANT_LOAN";

//    GROUP_BANK_RESPONSIBILITY_DATA
    String SET_GROUP_BANK_RESPONSIBILITY_DATA = "SET_GROUP_BANK_RESPONSIBILITY_DATA";

    String DRAFT_SERIAL = "DRAFT_SERIAL";
    String CREDIT_SECRET_TABLE = "CREDIT_SECRET_TABLE";
    String CREDIT = "اعتبار اسنادی";
    String ILC_CREDIT = "اعتبار اسنادی داخلی (ریالی)";
    String IEL_CREDIT = "اعتبار اسنادی داخلی (ریالی-صادراتی)";
    String BILL_OF_EXCHANGE = "برات";
    String ORDER_REGISTRATION = "ثبت سفارش";

    String CERTIFIED_CHEQUE="CERTIFIED_CHEQUE";
    String ISSUABLE_CHEQUE="ISSUABLE_CHEQUE";
    String COMMON_CHEQUE="COMMON_CHEQUE";

    // Heidari 18 Jun 2014
    String OTHER_BANK_SIGNATURE_INSERT = "OTHER_BANK_SIGNATURE_INSERT";
    String OTHER_BANK_SIGNATURE_UPDATE = "OTHER_BANK_SIGNATURE_UPDATE";
    String OTHER_BANK_SIGNATURE_INACTIVE = "OTHER_BANK_SIGNATURE_INACTIVE";
    String OTHER_BANK_SIGNATURE_ACTIVE = "OTHER_BANK_SIGNATURE_ACTIVE";

    String OTHER_BANK_SIGNATURE_STATUS_ENABLE = "OTHER_BANK_SIGNATURE_STATUS_ENABLE";
    String OTHER_BANK_SIGNATURE_STATUS_DISABLE = "OTHER_BANK_SIGNATURE_STATUS_DISABLE";

    String OTHER_BANK_SIGNATURE_LEVEL_ONE = "OTHER_BANK_SIGNATURE_LEVEL_ONE";
    String OTHER_BANK_SIGNATURE_LEVEL_TWO = "OTHER_BANK_SIGNATURE_LEVEL_TWO";

    String REGISTER_CT_VIAFILE = "REGISTER_CT_VIAFILE";
    String REGISTER_SPECIAL_CT = "REGISTER_SPECIAL_CT";


    String REGISTER_GROUP_PAYMENT = "REGISTER_GROUP_PAYMENT";
    String REGISTER_TRANSFER_DEPOSIT_TO_OTHER_BRANCH = "REGISTER_TRANSFER_DEPOSIT_TO_OTHER_BRANCH";


    //Debt Collection
    String DEBTCOLLECTION_FILE = "DEBTCOLLECTION_FILE";


    // Empty String && SpaceString
    String EMPTY_STRING = "";
    String SPACE_STRING = " ";
    String DASH_SEPARATOR = "-";
    String DASH_SEPARATOR_WITH_SPACE = " - ";
    String UNDERLINE_SEPARATOR = "_";
    String SLASH_CHARACTER = "/";
    String COMMA_CHARACTER = " , ";
    String COMMA_WITHOUT_SPACE_CHARACTER = ",";
    String NUMBER_SIGN_CHARACTER = "#";
    String POSITIVE_SIGN = "+";
    String NEGATIVE_SIGN = "-";
    String TRUE_STRING = "true";
    String FALSE_STRING = "false";
    String LEFT_PARENTHESIS = "(";
    String RIGHT_PARENTHESIS = ")";
    String COLON_CHARACTER = ":";
    String DOT_CHARACTER = ".";
    String SEMICOLON_CHARACTER = ";";
    String AT_SIGN_CHARACTER = "@";
    String STAR_CHARACTER = "*";
    String DOLLAR_SIGN_CHARACTER = "$";
    String EQUAK_SIGN_CHARACTER = "=";



    //File Format
    String XLS_FILE_FORMAT = "xls";
    String TXT_FILE_FORMAT = "txt";

    //GENERATE MANDATE REQUEST ID
    String GENERATE_MANDATE_REQUEST_ID = "GENERATE_MANDATE_REQUEST_ID";

    String GTR_SERVICE = "GTR_SERVICE";
    String INTEREST_GTR_SERVICE = "INTEREST_GTR_SERVICE";
    String GROUP_PAYMENT_GTR_SERVICE = "GROUP_PAYMENT_GTR_SERVICE";
    String SALARY_GTR_SERVICE = "SALARY_GTR_SERVICE";
    String SUBSIDY_GTR_SERVICE = "SUBSIDY_GTR_SERVICE";
    String MORTGAGE_UNBLOCK_GTR_SERVICE = "MORTGAGE_UNBLOCK_GTR_SERVICE";
    String INSTALLMENT_GTR_SERVICE = "INSTALLMENT_GTR_SERVICE";
    String VOJOOH_INSTALLMENT_GTR_SERVICE = "VOJOOH_INSTALLMENT_GTR_SERVICE";
    String LOAN_CUSTOMER_BASED_GENERAL_GTR_SERVICE = "LOAN_CUSTOMER_BASED_GENERAL_GTR_SERVICE";
    String LOAN_FIN_AND_REG_GENERAL_GTR_SERVICE = "LOAN_FIN_AND_REG_GENERAL_GTR_SERVICE";
    String SHORT_TERM_DEPOSIT_PAYMENT_INTEREST_GTR_SERVICE = "SHORT_TERM_DEPOSIT_PAYMENT_INTEREST_GTR_SERVICE";
    String LONG_TERM_DEPOSIT_PAYMENT_INTEREST_GTR_SERVICE = "LONG_TERM_DEPOSIT_PAYMENT_INTEREST_GTR_SERVICE";
    String SHORT_TERM_DEPOSIT_PAYMENT_SPECIAL_INTEREST_GTR_SERVICE = "SHORT_TERM_DEPOSIT_PAYMENT_SPECIAL_INTEREST_GTR_SERVICE";
    String LONG_TERM_DEPOSIT_PAYMENT_SPECIAL_INTEREST_GTR_SERVICE = "LONG_TERM_DEPOSIT_PAYMENT_SPECIAL_INTEREST_GTR_SERVICE";
    String OTHER_GTR_SERVICE = "OTHER_GTR_SERVICE";
    String GTR_CONSUMER = "GTR_CONSUMER";
    String GTR_PRODUCER = "GTR_PRODUCER";

    //transaction type
    String ACH_TRANSACTION = "ACH_TRANSACTION";
    String SATNA_TRANSACTION = "SATNA_TRANSACTION";
    String INTERNAL_TRANSACTION = "INTERNAL_TRANSACTION";

    String GATE_TYPE_CORE = "CORE";


    // DYNAMIC_PAGE_ENTRY
    String SEQUENCE_NAME = "SEQUENCE_NAME";
    String DEST_PAGE_ENTRY_NAME = "DEST_PAGE_ENTRY_NAME";
    String REQUIRED_AFTER_DB_GETS = "REQUIRED_AFTER_DB_GETS";
    String REQUIRED_BEFORE_DB_GETS = "REQUIRED_BEFORE_DB_GETS";
    String OPTIONAL_AFTER_DB_GETS = "OPTIONAL_AFTER_DB_GETS";
    String OPTIONAL_BEFORE_DB_GETS = "OPTIONAL_BEFORE_DB_GETS";

    String META_DATA_TRANSACTION_TYPE = "META_DATA_TRANSACTION_TYPE";
    String SYSTEM_META_DATA = "SYSTEM_META_DATA";
    String META_DATA_SCHEDULED_PAYMENT_CUASE_TYPE = "META_DATA_SCHEDULED_PAYMENT_CUASE_TYPE";

    // ILC_TRANSACTION_TYPE
    String ILC_ISSUE_CONTRACT = "ILC_ISSUE_CONTRACT";
    String ILC_RECEIVE_CASH_MAIN_ACCOUNT = "ILC_RECEIVE_CASH_MAIN_ACCOUNT";
    String ILC_ISSUE_GUARANTEE = "ILC_ISSUE_GUARANTEE";
    String ILC_REGISTER_DOCUMENT_RECEIPT = "ILC_REGISTER_DOCUMENT_RECEIPT";
    String ILC_PAY_DONE = "ILC_PAY_DONE";
    String ILC_COSTS = "ILC_COSTS";
    String ILC_DISCOUNT = "ILC_DISCOUNT";
    String ILC_COMMIT = "ILC_COMMIT";
    String ILC_SETTLE = "ILC_SETTLE";
    String ILC_IEL_RECEIVE_PRE_PAY = "ILC_IEL_RECEIVE_PRE_PAY";
    String ILC_IEL_PAY_PRE_PAY = "ILC_IEL_PAY_PRE_PAY";
    String ILC_IEL_COSTS = "ILC_IEL_COSTS";
    String ILC_CONFIRM_IEL_RECEIPT = "ILC_CONFIRM_IEL_RECEIPT";
    String ILC_SEND_IEL_RECEIPT = "ILC_SEND_IEL_RECEIPT";
    String ILC_IEL_REJECT_BY_CUSTOMER = "ILC_IEL_REJECT_BY_CUSTOMER";
    String ILC_IEL_RETURN_DOC = "ILC_IEL_RETURN_DOC";
    String ILC_IEL_DISCOUNT = "ILC_IEL_DISCOUNT";
    String ILC_IEL_COMMIT = "ILC_IEL_COMMIT";
    String ILC_IEL_RECEIVE_CASH = "ILC_IEL_RECEIVE_CASH";
    String ILC_IEL_PAY_DONE = "ILC_IEL_PAY_DONE";
    String ILC_RETURN_EXCESS_PAY = "ILC_RETURN_EXCESS_PAY";
    String ILC_RETURN_CONTRACT_ISSUE = "ILC_RETURN_CONTRACT_ISSUE";
    String ILC_RETURN_PRE_CURRENCY_TRANS = "ILC_RETURN_PRE_CURRENCY_TRANS";
    String ILC_RETURN_CONVERT_DEBT = "ILC_RETURN_CONVERT_DEBT";
    String ILC_RETURN_INTER_PAYMENT_CONVERT_DEBT = "ILC_RETURN_INTER_PAYMENT_CONVERT_DEBT";
    String ILC_RETURN_CASH = "ILC_RETURN_CASH";
    String ILC_RECEIVE_CASH = "ILC_RECEIVE_CASH";
    String ILC_UPDATE_DOC_RECEIPT = "ILC_UPDATE_DOC_RECEIPT";
    String ILC_CONVERT_DEBT = "ILC_CONVERT_DEBT";
    String ILC_INTER_PAY_CONVERT_DEBT = "ILC_INTER_PAY_CONVERT_DEBT";
    String ILC_REALIZE_COMMISSION = "ILC_REALIZE_COMMISSION";
    String ILC_PRE_CURRENCY_TRANS = "ILC_PRE_CURRENCY_TRANS";
    String ILC_DELIVER_DOC = "ILC_DELIVER_DOC";
    String ILC_CANCEL_DOC = "ILC_CANCEL_DOC";
    String ILC_DELETE_DOC = "ILC_DELETE_DOC";
    String ILC_RETURN_ILC_PAY_DONE = "ILC_RETURN_ILC_PAY_DONE";
    String ILC_UPDATE_ILC_CREDIT = "ILC_UPDATE_ILC_CREDIT";
    String ILC_COMPLETE_ILC_CREDIT = "ILC_COMPLETE_ILC_CREDIT";
    String ILC_RETURN_ILC_COMMIT = "ILC_RETURN_ILC_COMMIT";
    String ILC_SETTLE_ILC_DISCOUNT = "ILC_SETTLE_ILC_DISCOUNT";
    String ILC_SETTLE_THIRD_DISCOUNT = "ILC_SETTLE_THIRD_DISCOUNT";
    String ILC_RECEIVE_COMMISSION_DISCOUNT = "ILC_RECEIVE_COMMISSION_DISCOUNT";
    String ILC_REVERSE_COMMISSION_DISCOUNT = "ILC_REVERSE_COMMISSION_DISCOUNT";
    String ILC_SETTLE_IEL_DISCOUNT = "ILC_SETTLE_IEL_DISCOUNT";
    String ILC_RETURN_SETTLE_ILC_DISCOUNT = "ILC_RETURN_SETTLE_ILC_DISCOUNT";
    String ILC_RETURN_SETTLE_IEL_DISCOUNT = "ILC_RETURN_SETTLE_IEL_DISCOUNT";
    String ILC_RETURN_IEL_COMMIT = "ILC_RETURN_IEL_COMMIT";
    String ILC_IEL_RETURNED_REJECT = "ILC_IEL_RETURNED_REJECT";
    String ILC_IEL_RETURN_REJECT_BY_CUSTOMER = "ILC_IEL_RETURN_REJECT_BY_CUSTOMER";
    String ILC_ADD_ILC_DYN_COMMISSION_COM = "ILC_ADD_ILC_DYN_COMMISSION_COM";
    String ILC_ADD_ILC_DYN_COMMISSION_DISCOUNT_COM = "ILC_ADD_ILC_DYN_COMMISSION_DISCOUNT_COM";
    String ILC_COMPLETE_ILC_CREDIT_COM = "ILC_COMPLETE_ILC_CREDIT_COM";
    String ILC_UPDATE_ILC_CREDIT_COM = "ILC_UPDATE_ILC_CREDIT_COM";
    String ILC_EXTEND_ILC_CREDIT_COM = "ILC_EXTEND_ILC_CREDIT_COM";
    String ILC_DOC_RECEIPT_ILC_CREDIT_COM = "ILC_DOC_RECEIPT_ILC_CREDIT_COM";
    String ILC_DELETE_ILC_CREDIT_COM = "ILC_DELETE_ILC_CREDIT_COM";
    String ILC_REC_OTHER_COMMISSION_COM = "ILC_REC_OTHER_COMMISSION_COM";
    String IEL_REC_OTHER_COMMISSION_COM = "IEL_REC_OTHER_COMMISSION_COM";
    String ILC_REV_OTHER_COMMISSION_COM = "ILC_REV_OTHER_COMMISSION_COM";
    String IEL_REV_OTHER_COMMISSION_COM = "IEL_REV_OTHER_COMMISSION_COM";
    String ILC_ADD_IEL_DYN_COMMISSION_DISCOUNT_COM = "ILC_ADD_IEL_DYN_COMMISSION_DISCOUNT_COM";
    String ILC_ADD_IEL_TRANs_COMMISSION_DISCOUNT_COM = "ILC_ADD_IEL_TRANs_COMMISSION_DISCOUNT_COM";
    String ILC_IEL_DOC_RECEIPT_COM = "ILC_IEL_DOC_RECEIPT_COM";
    String ILC_IEL_CREDIT_COMPLETE_COM = "ILC_IEL_CREDIT_COMPLETE_COM";
    String ILC_CREDIT_TRANSFER_COM = "ILC_CREDIT_TRANSFER_COM";
    String ILC_UPDATE_IEL_CREDIT_COM = "ILC_UPDATE_IEL_CREDIT_COM";
    String ILC_RETURN_DOC_CREDIT_COM = "ILC_RETURN_DOC_CREDIT_COM";
    String ILC_CLEAR_CREDIT_COM = "ILC_CLEAR_CREDIT_COM";
    String ILC_IEL_COST_REV = "ILC_IEL_COST_REV";
    String ILC_DELETE_IEL_DOC_RECEIPT_REV = "ILC_DELETE_IEL_DOC_RECEIPT_REV";
    String ILC_RETURN_SEND_IEL_DOC_RECEIPT_REV = "ILC_RETURN_SEND_IEL_DOC_RECEIPT_REV";
    String ILC_RETURN_ACCEPT_IEL_DOC_RECEIPT_REV = "ILC_RETURN_ACCEPT_IEL_DOC_RECEIPT_REV";
    String ILC_RET_ACCEPT_BY_CUSTOMER_IEL_DOC_RECEIPT_REV = "ILC_RET_ACCEPT_BY_CUSTOMER_IEL_DOC_RECEIPT_REV";
    String ILC_RET_DOC_IEL_DOC_RECEIPT_REV = "ILC_RET_DOC_IEL_DOC_RECEIPT_REV";
    String ILC_RET_IEL_PRE_CURRENCY_CASH_REV = "ILC_RET_IEL_PRE_CURRENCY_CASH_REV";
    String ILC_RETURN_IEL_PRE_CURRENCY_PAY_REV = "ILC_RETURN_IEL_PRE_CURRENCY_PAY_REV";
    String ILC_RET_IEL_DOC_RECEIPT_CASH_REV = "ILC_RET_IEL_DOC_RECEIPT_CASH_REV";
    String ILC_RET_IEL_DOC_RECEIPT_PAY_TO_BENEFI_REV = "ILC_RET_IEL_DOC_RECEIPT_PAY_TO_BENEFI_REV";
    String ILC_DELETE_ILC_CREDIT_REV = "ILC_DELETE_ILC_CREDIT_REV";
    String ILC_CANCEL_CONTRACT_ILC_CREDIT_REV = "ILC_CANCEL_CONTRACT_ILC_CREDIT_REV";
    String ILC_CANCEL_ILC_COSTS_REV = "ILC_CANCEL_ILC_COSTS_REV";
    String ILC_CANCEL_ILC_GUARANTEE_REV = "ILC_CANCEL_ILC_GUARANTEE_REV";
    String ILC_RET_EXCESS_PAY_REV = "ILC_RET_EXCESS_PAY_REV";
    String ILC_RET_ILC_DOC_RECEIPT_REV = "ILC_RET_ILC_DOC_RECEIPT_REV";
    String ILC_DELETE_ILC_DOC_RECEIPT_REV = "ILC_DELETE_ILC_DOC_RECEIPT_REV";
    String ILC_CANCEL_DELIV_TO_CUSTOMER_DOC_RECEIPT_REV = "ILC_CANCEL_DELIV_TO_CUSTOMER_DOC_RECEIPT_REV";
    String ILC_RETURN_ILC_CLEAR_CREDIT_REV = "ILC_RETURN_ILC_CLEAR_CREDIT_REV";
    String ILC_RET_DOC_RECEIPT_CURRENCY_TRANS_REV = "ILC_RET_DOC_RECEIPT_CURRENCY_TRANS_REV";
    String ILC_RETURN_REALIZE_COMMISSION_REV = "ILC_RETURN_REALIZE_COMMISSION_REV";
    String ILC_MERGE_BRANCH_TRANS_ACC_AMOUNT = "ILC_MERGE_BRANCH_TRANS_ACC_AMOUNT";
    String ILC_THIRD_DISCOUNT_DISCOUNT = "ILC_THIRD_DISCOUNT_DISCOUNT";
    String ILC_ADD_IEL_CREDIT_COM = "ILC_ADD_IEL_CREDIT_COM";

    String ILC_CREDIT_NUMBER_BASIC_INFOS = "ILC_CREDIT_NUMBER_BASIC_INFOS";
    String ILC_CREDIT_START_DATE_BASIC_INFOS = "ILC_CREDIT_START_DATE_BASIC_INFOS";
    String ILC_CREDIT_END_DATE_BASIC_INFOS = "ILC_CREDIT_END_DATE_BASIC_INFOS";
    String ILC_CREDIT_BRANCH_BASIC_INFOS = "ILC_CREDIT_BRANCH_BASIC_INFOS";
    String ILC_CREDIT_OPERATIONAL_BRANCH_BASIC_INFOS = "ILC_CREDIT_OPERATIONAL_BRANCH_BASIC_INFOS";
    String ILC_CREDIT_CUSTOMER_NUMBER_BASIC_INFOS = "ILC_CREDIT_CUSTOMER_NUMBER_BASIC_INFOS";
    String ILC_CREDIT_CENTRAL_BANK_CODE_BASIC_INFOS = "ILC_CREDIT_CENTRAL_BANK_CODE_BASIC_INFOS";
    String ILC_RECEIPT_SERIAL_PARAM = "ILC_RECEIPT_SERIAL_PARAM";
    String ILC_AMOUNT_PARAM = "ILC_AMOUNT_PARAM";
    String ILC_TYPE_PARAM = "ILC_TYPE_PARAM";
    String ILC_COMMENT_PARAM = "ILC_COMMENT_PARAM";
    String ILC_BASIC_INFO_PARAM = "ILC_BASIC_INFO_PARAM";


    // DEPOSIT GROUP OPERATION
    String DEPOSIT_TRANSACTION_TYPE_GROUP_PAYMENT = "DEPOSIT_GROUP_PAYMENT";
    String DEPOSIT_TRANSACTION_TYPE_GROUP_PAYMENT_TOPIC = "DEPOSIT_GROUP_PAYMENT_TOPIC";
    String DEPOSIT_TRANSACTION_TYPE_SALARY_PAYMENT = "DEPOSIT_SALARY_PAYMENT";
    String DEPOSIT_TRANSACTION_TYPE_SALARY_PAYMENT_TOPIC = "DEPOSIT_SALARY_PAYMENT_TOPIC";
    String DEPOSIT_TRANSACTION_TYPE_SUBSIDY_PAYMENT = "DEPOSIT_SUBSIDY_PAYMENT";
    String DEPOSIT_TRANSACTION_TYPE_OFFLINE_SCRIPTS = "DEPOSIT_OFFLINE_SCRIPTS";
    String DEPOSIT_TRANSACTION_TYPE_GROUP_WITHDRAW = "DEPOSIT_GROUP_WITHDRAW";
    String DEPOSIT_TRANSACTION_TYPE_GROUP_WITHDRAW_PONY = "DEPOSIT_GROUP_WITHDRAW_PONY";
    String DEPOSIT_TRANSACTION_TYPE_GROUP_PAYMENT_REVERT = "DEPOSIT_GROUP_PAYMENT_REVERT";
    String DEPOSIT_TRANSACTION_TYPE_SALARY_PAYMENT_REVERT = "DEPOSIT_SALARY_PAYMENT_REVERT";
    String DEPOSIT_TRANSACTION_TYPE_GROUP_PAYMENT_FAST_COMMISSION = "DEPOSIT_GROUP_PAYMENT_FAST_COMMISSION";
    String DEPOSIT_TRANSACTION_TYPE_GROUP_PAYMENT_REVERT_FAST_COMMISSION = "DEPOSIT_GROUP_PAYMENT_REVERT_FAST_COMMISSION";

    //**************************Deposit Transaction Types**************************
    String DEP_TRANSFER_AMOUNT_FROM_MAIN_TO_DECEASED_AND_INCAPABLE_ACCOUNT = "DEP_TRANSFER_AMOUNT_FROM_MAIN_TO_DECEASED_AND_INCAPABLE_ACCOUNT";
    String DEP_TRANSFER_AMOUNT_FROM_DECEASED_AND_INCAPABLE_TO_UNCERTAIN_ACCOUNT = "DEP_TRANSFER_AMOUNT_FROM_DECEASED_AND_INCAPABLE_TO_UNCERTAIN_ACCOUNT";
    String DEP_TRANSFER_AMOUNT_FROM_DECEASED_AND_INCAPABLE_TO_MAIN_ACCOUNT = "DEP_TRANSFER_AMOUNT_FROM_DECEASED_AND_INCAPABLE_TO_MAIN_ACCOUNT";
    String DEP_TRANSFER_AMOUNT_FROM_UNCERTAIN_TO_MAIN_ACCOUNT = "DEP_TRANSFER_AMOUNT_FROM_UNCERTAIN_TO_MAIN_ACCOUNT";
    String DEP_CLOSED_DEPOSITS_SETTLEMENT_END_OF_YEAR_INTEREST = "DEP_CLOSED_DEPOSITS_SETTLEMENT_END_OF_YEAR_INTEREST";
    String DEP_CLOSE_DEPOSIT_PHOENIX = "DEP_CLOSE_DEPOSIT_PHOENIX";
    String DEP_CLOSE_DEPOSIT_INTEREST_PHOENIX = "DEP_CLOSE_DEPOSIT_INTEREST_PHOENIX";
    String DEP_DEPOSIT_INTEREST_PHOENIX = "DEP_DEPOSIT_INTEREST_PHOENIX";
    String DEP_DEPOSIT_SPECIAL_INTEREST_PHOENIX = "DEP_DEPOSIT_SPECIAL_INTEREST_PHOENIX";
    String DEP_TRANSFER_MONEY_PHOENIX = "DEP_TRANSFER_MONEY_PHOENIX";
    String DEP_BUY_PARTNERSHIP_DOCUMENTS = "DEP_BUY_PARTNERSHIP_DOCUMENTS";
    String DEP_BUY_PARTNERSHIP_DOCUMENT = "DEP_BUY_PARTNERSHIP_DOCUMENT";
    String DEP_TRANSFER_MONEY = "DEP_TRANSFER_MONEY";
    String DEP_DEPOSIT_SEDIMENT_PER_CURRENCY = "DEP_DEPOSIT_SEDIMENT_PER_CURRENCY";
    String DEP_ISSUE_PARTNERSHIP_DOCUMENT = "DEP_ISSUE_PARTNERSHIP_DOCUMENT";
    String DEP_PONY_PARTNERSHIP_DOCUMENT = "DEP_PONY_PARTNERSHIP_DOCUMENT";
    String DEP_PONY_PARTNERSHIP_DOCUMENTS_COUPONS = "DEP_PONY_PARTNERSHIP_DOCUMENTS_COUPONS";
    String DEP_PONY_PARTNERSHIP_DOCUMENTS= "DEP_PONY_PARTNERSHIP_DOCUMENTS";
    String DEP_COMMITMENT_ON_ACCOUNT_INTEREST = "DEP_COMMITMENT_ON_ACCOUNT_INTEREST";
    String DEP_COMMITMENT_ON_ACCOUNT_INTEREST_MACRO_PHOENIX = "DEP_COMMITMENT_ON_ACCOUNT_INTEREST_MACRO_PHOENIX";
    String DEP_ON_ACCOUNT_INTEREST_CONTRADICTION_REMOVAL = "DEP_ON_ACCOUNT_INTEREST_CONTRADICTION_REMOVAL";
    String DEP_SPECIAL_DEPOSIT_TYPES_INTEREST= "DEP_SPECIAL_DEPOSIT_TYPES_INTEREST";
    String DEP_PERIODIC_INTEREST = "DEP_PERIODIC_INTEREST";
    String DEP_DEPOSIT_INTEREST_MANUALLY = "DEP_DEPOSIT_INTEREST_MANUALLY";
    String DEP_INTEREST_MANUALLY_FOR_CLOSED_OR_EXTENDED_DEPOSIT = "DEP_INTEREST_MANUALLY_FOR_CLOSED_OR_EXTENDED_DEPOSIT";
    String DEP_UPDATE_ISSUED_PARTNERSHIP_DOCUMENT = "DEP_UPDATE_ISSUED_PARTNERSHIP_DOCUMENT";
    String DEP_PAY_OFF_INTEREST_DEPOSIT = "DEP_PAY_OFF_INTEREST_DEPOSIT";
    String DEP_CLOSE_DEPOSIT= "DEP_CLOSE_DEPOSIT";
    String DEP_ITERATIVE_CLOSE_DEPOSIT= "DEP_ITERATIVE_CLOSE_DEPOSIT";
    String DEP_MANUAL_INTEREST_DEPOSIT= "DEP_MANUAL_INTEREST_DEPOSIT";
    String DEP_PONY_NOT_DEPOSITED_INTEREST= "DEP_PONY_NOT_DEPOSITED_INTEREST";
    String DEP_REGISTER_PARTNERSHIP_DOCUMENTS_RECEIVED_FROM_CENTRAL_CLEAR = "DEP_REGISTER_PARTNERSHIP_DOCUMENTS_RECEIVED_FROM_CENTRAL_CLEAR";
    String DEP_SELL_PARTNERSHIP_DOCUMENT = "DEP_SELL_PARTNERSHIP_DOCUMENT";
    String DEP_RESALE_PARTNERSHIP_DOCUMENT = "DEP_RESALE_PARTNERSHIP_DOCUMENT";
    String DEP_TEMP_SELL_PARTNERSHIP_DOCUMENT = "DEP_TEMP_SELL_PARTNERSHIP_DOCUMENT";
    String DEP_SETTLE_OTHERS_PARTNERSHIP_DOCUMENTS_SENT_TO_CLEAR = "DEP_SETTLE_OTHERS_PARTNERSHIP_DOCUMENTS_SENT_TO_CLEAR";
    String DEP_SETTLE_PARTNERSHIP_DOCUMENT_BOOK = "DEP_SETTLE_PARTNERSHIP_DOCUMENT_BOOK";
    String DEP_SETTLE_ZEMAND_ZRAFT = "DEP_SETTLE_ZEMAND_ZRAFT";
    String DEP_DEPOSIT_MANAGEMENT = "DEP_DEPOSIT_MANAGEMENT";
    String DEP_STOCK_TRANSFER_MONEY_NEW = "DEP_STOCK_TRANSFER_MONEY_NEW";
    String DEP_STORED_DEPOSIT_DEPOSIT_MONEY = "DEP_STORED_DEPOSIT_DEPOSIT_MONEY";
    String DEP_OPEN_DEPOSIT_FOR_TRANSMIT_DEPOSIT_CERTIFICATION = "DEP_OPEN_DEPOSIT_FOR_TRANSMIT_DEPOSIT_CERTIFICATION";
    String DEP_BLOCK_DEPOSIT = "DEP_BLOCK_DEPOSIT";
    String DEP_INTEREST_BLOCK_DEPOSIT = "DEP_INTEREST_BLOCK_DEPOSIT";
    String DEP_CANCEL_BLOCK_DEPOSIT = "DEP_CANCEL_BLOCK_DEPOSIT";
    String DEP_CANCEL_INTEREST_BLOCK_DEPOSIT = "DEP_CANCEL_INTEREST_BLOCK_DEPOSIT";
    String DEP_TRANSFER_DEPOSIT_TO_NEW_BRANCH = "DEP_TRANSFER_DEPOSIT_TO_NEW_BRANCH";
    String DEP_PONY_ALL_END_OF_YEAR_INTEREST_ACCOUNTS = "DEP_PONY_ALL_END_OF_YEAR_INTEREST_ACCOUNTS";
    String DEP_PAY_INTEREST_STOCK = "DEP_PAY_INTEREST_STOCK";
    String DEP_SEDIMENT = "DEP_SEDIMENT";
    String DEP_TRANSFER_ACCOUNTS_AMOUNT_IN_EXTEND_DEPOSIT = "DEP_TRANSFER_ACCOUNTS_AMOUNT_IN_EXTEND_DEPOSIT";
    String DEP_TRANSFER_END_OF_YEAR_ACCOUNT_REMAIN_AMOUNT = "DEP_TRANSFER_END_OF_YEAR_ACCOUNT_REMAIN_AMOUNT";
    String DEP_TRANSFER_MONEY_FROM_ACCOUNT_TO_ACCOUNT = "DEP_TRANSFER_MONEY_FROM_ACCOUNT_TO_ACCOUNT";
    String DEP_SCHEDULED_PAYMENT_DEPOSITS = "DEP_SCHEDULED_PAYMENT_DEPOSITS";
    String DEP_SPECIAL_DEPOSIT_TYPES_INTEREST_FOR_CLOSED_DEPOSITS = "DEP_SPECIAL_DEPOSIT_TYPES_INTEREST_FOR_CLOSED_DEPOSITS";
    String DEP_YARANE_PAYMENT_LOADER = "DEP_YARANE_PAYMENT_LOADER";
    String DEP_TRANSFER_END_OF_YEAR_ACCOUNT_AMOUNT_TO_INTEREST_ACCOUNT = "DEP_TRANSFER_END_OF_YEAR_ACCOUNT_AMOUNT_TO_INTEREST_ACCOUNT";
    String DEP_BILL_FORCED_TRANSFER_MONEY = "DEP_BILL_FORCED_TRANSFER_MONEY";
    String DEP_STOCK_TRANSFER_MONEY = "DEP_STOCK_TRANSFER_MONEY";
    String DEP_SIMPLE_TRANSFER_MONEY = "DEP_SIMPLE_TRANSFER_MONEY";
    String DEP_START_TRANSFER_MONEY = "DEP_START_TRANSFER_MONEY";
    String DEP_TRANSFER_AMOUNT_TO_SUPPORTER_PER_CURRENCY = "DEP_TRANSFER_AMOUNT_TO_SUPPORTER_PER_CURRENCY";
    String DEP_RE_BUY_OTHERS_INTEREST_INCLUSIVE_DOC = "DEP_RE_BUY_OTHERS_INTEREST_INCLUSIVE_DOC";
    String DEP_RE_BUY_OURS_INTEREST_INCLUSIVE_DOC = "DEP_RE_BUY_OURS_INTEREST_INCLUSIVE_DOC";
    String DEP_RE_BUY_OURS_PARTNERSHIP_DOC = "DEP_RE_BUY_OURS_PARTNERSHIP_DOC";
    String DEP_RE_BUY_PARTNERSHIP_DOC = "DEP_RE_BUY_PARTNERSHIP_DOC";
    String DEP_CANCEL_DEPOSIT_TRANSACTION = "DEP_CANCEL_DEPOSIT_TRANSACTION";
    String DEP_DEPOSIT_MAIN_ACCOUNT_FINDER = "DEP_DEPOSIT_MAIN_ACCOUNT_FINDER";
    String DEP_DEPOSIT_SUPPORTER = "DEP_DEPOSIT_SUPPORTER";
    String DEP_OPEN_DEPOSIT = "DEP_OPEN_DEPOSIT";
    String DEP_OPEN_DEPOSIT_INTEREST = "DEP_OPEN_DEPOSIT_INTEREST";
    String DEP_PONY_INTEREST_INCLUSIVE_PARTNERSHIP_DOCUMENT = "DEP_PONY_INTEREST_INCLUSIVE_PARTNERSHIP_DOCUMENT";
    String DEP_SORTED_DEPOSIT_TRANSFORMATION = "DEP_SORTED_DEPOSIT_TRANSFORMATION";
    String DEP_SORTED_DEPOSIT_WITHDRAW_MONEY = "DEP_SORTED_DEPOSIT_WITHDRAW_MONEY";
    String DEP_TRANSFER_MONEY_IB = "DEP_TRANSFER_MONEY_IB";
    String DEP_UPDATE_ISSUED_INTEREST_INCLUSIVE_DOC = "DEP_UPDATE_ISSUED_INTEREST_INCLUSIVE_DOC";
    String DEP_ITERATIVE_INTEREST_DEPOSIT = "DEP_ITERATIVE_INTEREST_DEPOSIT";
    String DEP_INTEREST_INCLUSIVE_DOCUMENT_SETTLE = "DEP_INTEREST_INCLUSIVE_DOCUMENT_SETTLE";
    String DEP_INTEREST_INCLUSIVE_DOCUMENT_COMMITMENT_INTEREST = "DEP_INTEREST_INCLUSIVE_DOCUMENT_COMMITMENT_INTEREST";
    String DEP_INTEREST_INCLUSIVE_DOCUMENT_BANK_INTEREST = "DEP_INTEREST_INCLUSIVE_DOCUMENT_BANK_INTEREST";
    String DEP_INTEREST_INCLUSIVE_DOCUMENT_EXTERNAL_BANK_INTEREST = "DEP_INTEREST_INCLUSIVE_DOCUMENT_EXTERNAL_BANK_INTEREST";
    String DEP_INTEREST_DIFFERENCE_INTEREST = "DEP_INTEREST_DIFFERENCE_INTEREST";
    String DEP_STAMP = "DEP_STAMP";
    String DEP_DEPOSIT_INTEREST_SOURCE = "DEP_DEPOSIT_INTEREST_SOURCE";
    String DEP_DEPOSIT_UNCLAIMED = "DEP_DEPOSIT_UNCLAIMED";
    String DEP_TRANSFER_AMOUNT_FROM_UNCLAIMED_TO_MAIN_ACCOUNT = "DEP_TRANSFER_AMOUNT_FROM_UNCLAIMED_TO_MAIN_ACCOUNT";
    String DEP_TRANSFER_AMOUNT_FROM_MAIN_TO_UNCLAIMED_ACCOUNT = "DEP_TRANSFER_AMOUNT_FROM_MAIN_TO_UNCLAIMED_ACCOUNT";
    String DEP_COUPON_INTEREST = "DEP_COUPON_INTEREST";
    String DEP_PARTNERSHIP_DOCUMENT_INTEREST = "DEP_PARTNERSHIP_DOCUMENT_INTEREST";
    String DEP_INTEREST_INCLUSIVE_DOCUMENT_RESOURCE = "DEP_INTEREST_INCLUSIVE_DOCUMENT_RESOURCE";
    String DEP_REVERSE_PARTNERSHIP_DOCUMENT = "DEP_REVERSE_PARTNERSHIP_DOCUMENT";
    String DEP_REVERSE_CLOSE_DEPOSIT_DOCUMENT = "DEP_REVERSE_CLOSE_DEPOSIT_DOCUMENT";
    String DEP_REVERSE_DEPOSIT_DOCUMENT = "DEP_REVERSE_DEPOSIT_DOCUMENT";
    String DEP_WITHDRAW_SUPPORTER_DEPOSIT = "DEP_WITHDRAW_SUPPORTER_DEPOSIT";
    String DEP_TRANSFER_SUPPORTER_DEPOSIT = "DEP_TRANSFER_SUPPORTER_DEPOSIT";
    String DEP_INTEREST_ON_EXTEND_DEPOSIT = "DEP_INTEREST_ON_EXTEND_DEPOSIT";
    String DEP_WITHDRAW_FROM_LOAN_ACCOUNT = "DEP_WITHDRAW_FROM_LOAN_ACCOUNT";
    String DEP_DEPOSIT_TO_DEPOSIT_FROM_LOAN_ACCOUNT = "DEP_DEPOSIT_TO_DEPOSIT_FROM_LOAN_ACCOUNT";
    String DEP_WITHDRAW_ISSUE_DOCUMENT_WITH_BOX = "DEP_WITHDRAW_ISSUE_DOCUMENT_WITH_BOX";
    String DEP_DEPOSIT_ISSUE_DOCUMENT_WITH_BOX = "DEP_DEPOSIT_ISSUE_DOCUMENT_WITH_BOX";
    String DEP_ISSUE_DOCUMENT_WITHOUT_BOX = "DEP_ISSUE_DOCUMENT_WITHOUT_BOX";
    String DEP_SPECIAL_ISSUE_DOCUMENT = "DEP_SPECIAL_ISSUE_DOCUMENT";
    String DEP_SPECIAL_ISSUE_DOCUMENT_FOR_SWITCH_FOR_SWITCH = "DEP_SPECIAL_ISSUE_DOCUMENT_FOR_SWITCH_FOR_SWITCH";
    String DEP_CHANGE_DEPOSIT_CURRENCY = "DEP_CHANGE_DEPOSIT_CURRENCY";
    //****************************************************

    //**************************Deposit Commission Transaction Types**************************
    String DEP_CANCEL_BLOCK_DEPOSIT_COM = "DEP_CANCEL_BLOCK_DEPOSIT_COM";
    String DEP_WITHDRAW_STAGNANT_AMOUNT_COM = "DEP_WITHDRAW_STAGNANT_AMOUNT_COM";
    String DEP_DEPOSIT_TRANSACTIONS_COM = "DEP_DEPOSIT_TRANSACTIONS_COM";
    String DEP_ISSUE_VOUCHER_COM = "DEP_ISSUE_VOUCHER_COM";
    String DEP_RESULT_PRINT_PERFERAJ_DEPOSIT_COM = "DEP_RESULT_PRINT_PERFERAJ_DEPOSIT_COM";
    String DEP_BLOCK_DEPOSIT_COM = "DEP_BLOCK_DEPOSIT_COM";
    String DEP_ACTIVATE_DEPOSIT_SMS_INFO_COM = "DEP_ACTIVATE_DEPOSIT_SMS_INFO_COM";
    String DEP_DEPOSIT_TRANSMISSION_COM = "DEP_DEPOSIT_TRANSMISSION_COM";
    String DEP_EDIT_SOURCE_OF_CURRENCY_COM = "DEP_EDIT_SOURCE_OF_CURRENCY_COM";
    String DEP_OPEN_DEPOSIT_COM = "DEP_OPEN_DEPOSIT_COM";
    String DEP_UPDATE_DEPOSIT_SMS_INFO_COM = "DEP_UPDATE_DEPOSIT_SMS_INFO_COM";
    //****************************************************

    //**************************Deposit System Meta Data Dto Types**************************
    String DEP_SMD_DEPOSIT_LIMITATION_INFO = "DEP_SMD_DEPOSIT_LIMITATION_INFO";
    String DEP_SMD_DEPOSIT_UNCLAIMED = "DEP_SMD_DEPOSIT_UNCLAIMED";
    String DEP_SMD_CLOSE_DEPOSIT_PHOENIX = "DEP_SMD_CLOSE_DEPOSIT_PHOENIX";
    String DEP_SMD_CLOSE_DEPOSIT_INTEREST_PHOENIX = "DEP_SMD_CLOSE_DEPOSIT_INTEREST_PHOENIX";
    String DEP_SMD_CLOSE_DEPOSIT_INTEREST_AMOUNT_PHOENIX = "DEP_SMD_CLOSE_DEPOSIT_INTEREST_AMOUNT_PHOENIX";
    String DEP_SMD_DEPOSIT_INTEREST_PHOENIX = "DEP_SMD_DEPOSIT_INTEREST_PHOENIX";
    String DEP_SMD_TRANSFER_MONEY = "DEP_SMD_TRANSFER_MONEY";
    String DEP_SMD_OFFLINE_SCRIPTS = "DEP_SMD_OFFLINE_SCRIPTS";
    String DEP_SMD_SPECIAL_DEPOSIT_TYPES_INTEREST_FOR_CLOSED_DEPOSITS = "DEP_SMD_SPECIAL_DEPOSIT_TYPES_INTEREST_FOR_CLOSED_DEPOSITS";
    String DEP_SMD_SCHEDULED_PAYMENT_DEPOSITS = "DEP_SMD_SCHEDULED_PAYMENT_DEPOSITS";
    String DEP_SMD_YARANE_PAYMENT_LOADER = "DEP_SMD_YARANE_PAYMENT_LOADER";
    String DEP_SMD_ITERATIVE_INTEREST_DEPOSIT = "DEP_SMD_ITERATIVE_INTEREST_DEPOSIT";
    String DEP_SMD_CLOSE_DEPOSIT = "DEP_SMD_CLOSE_DEPOSIT";
    String DEP_SMD_INTEREST_COMMITMENT_INFO = "DEP_SMD_INTEREST_COMMITMENT_INFO";
    String DEP_SMD_CANCEL_BLOCK_DEPOSIT_COMMISSION = "DEP_SMD_CANCEL_BLOCK_DEPOSIT_COMMISSION";
    String DEP_SMD_WITHDRAW_STAGNANT_AMOUNT_COMMISSION = "DEP_SMD_WITHDRAW_STAGNANT_AMOUNT_COMMISSION";
    String DEP_SMD_TRANSFER_AMOUNT_TO_SUPPORTER_PER_CURRENCY = "DEP_SMD_TRANSFER_AMOUNT_TO_SUPPORTER_PER_CURRENCY";
    String DEP_SMD_BLOCK_DEPOSIT = "DEP_SMD_BLOCK_DEPOSIT";
    String DEP_SMD_UNBLOCK_DEPOSIT = "DEP_SMD_UNBLOCK_DEPOSIT";
    String DEP_SMD_EXTEND_DEPOSIT = "DEP_SMD_EXTEND_DEPOSIT";
    String DEP_SMD_INTEREST_ON_EXTEND_DEPOSIT = "DEP_SMD_INTEREST_ON_EXTEND_DEPOSIT";
    String DEP_SMD_ISSUE_VOUCHER_COMMISSION = "DEP_SMD_ISSUE_VOUCHER_COMMISSION";
    String DEP_SMD_DEPOSIT_TRANSACTIONS_COMMISSION = "DEP_SMD_DEPOSIT_TRANSACTIONS_COMMISSION";
    String DEP_SMD_ISSUE_SUPPORT_DOCUMENT= "DEP_SMD_ISSUE_SUPPORT_DOCUMENT";
    String DEP_SMD_ISSUE_TRANSFER_END_OF_YEAR_ACCOUNT_AMOUNT_TO_INTEREST_ACCOUNT = "DEP_SMD_ISSUE_TRANSFER_END_OF_YEAR_ACCOUNT_AMOUNT_TO_INTEREST_ACCOUNT";
    String DEP_SMD_ISSUE_PERFERAJ_COMMISSION = "DEP_SMD_ISSUE_PERFERAJ_COMMISSION";
    String DEP_SMD_ISSUE_OPENING_DEPOSIT = "DEP_SMD_ISSUE_OPENING_DEPOSIT";
    String DEP_SMD_ISSUE_OPENING_DEPOSIT_INTEREST = "DEP_SMD_ISSUE_OPENING_DEPOSIT_INTEREST";
    String DEP_SMD_BLOCK_DEPOSIT_COMMISSION = "DEP_SMD_BLOCK_DEPOSIT_COMMISSION";
    String DEP_SMD_OPEN_DEPOSIT_FOR_TRANSMIT_DEPOSIT_CERTIFICATION = "DEP_SMD_OPEN_DEPOSIT_FOR_TRANSMIT_DEPOSIT_CERTIFICATION" ;
    String DEP_SMD_TRANSFER_DEPOSIT_TO_NEW_BRANCH = "DEP_SMD_TRANSFER_DEPOSIT_TO_NEW_BRANCH";
    String DEP_SMD_GRANT_LOAN_TO_DEPOSIT = "DEP_SMD_GRANT_LOAN_TO_DEPOSIT";
    String DEP_SMD_UPDATE_DEPOSIT_SMS_INFO_COMMISSION = "DEP_SMD_UPDATE_DEPOSIT_SMS_INFO_COMMISSION";
    String DEP_SMD_OPEN_DEPOSIT_COMMISSION = "DEP_SMD_OPEN_DEPOSIT_COMMISSION";
    String DEP_SMD_BASIC_TRANSFER_MONEY = "DEP_SMD_BASIC_TRANSFER_MONEY";
    String DEP_SMD_SPECIAL_SERVICE = "DEP_SMD_SPECIAL_SERVICE";
    String DEP_SMD_SEND_SMS_INFO = "DEP_SMD_SEND_SMS_INFO";
    String DEP_SMD_DEPOSIT_INTEREST_INFO = "DEP_SMD_DEPOSIT_INTEREST_INFO";
    //****************************************************

    //**************************Deposit System Meta Data Parameters**************************
    String DEP_SMD_BRANCH_CODE = "DEP_SMD_BRANCH_CODE";
    String DEP_SMD_TOPIC_CODE = "DEP_SMD_TOPIC_CODE";
    String DEP_SMD_CURRENCY_SWIFT_CODE = "DEP_SMD_CURRENCY_SWIFT_CODE";
    String DEP_SMD_PREV_MAIN_AMOUNT = "DEP_SMD_PREV_MAIN_AMOUNT";
    String DEP_SMD_PREV_BLOCK_AMOUNT = "DEP_SMD_PREV_BLOCK_AMOUNT";
    String DEP_SMD_PREV_INT_BLOCK_AMOUNT = "DEP_SMD_PREV_INT_BLOCK_AMOUNT";
    String DEP_SMD_PREV_MORTGAGE_AMOUNT = "DEP_SMD_PREV_MORTGAGE_AMOUNT";
    String DEP_SMD_PREV_DEPOSIT_STATE = "DEP_SMD_PREV_DEPOSIT_STATE";
    String DEP_SMD_NEW_BLOCK_AMOUNT = "DEP_SMD_NEW_BLOCK_AMOUNT";
    String DEP_SMD_UNBLOCK_AMOUNT = "DEP_SMD_UNBLOCK_AMOUNT";
    String DEP_SMD_NEW_MORTGAGE_AMOUNT = "DEP_SMD_NEW_MORTGAGE_AMOUNT";
    String DEP_SMD_CANCEL_MORTGAGE_AMOUNT = "DEP_SMD_CANCEL_MORTGAGE_AMOUNT";
    String DEP_SMD_LETTER_DEADLINE = "DEP_SMD_LETTER_DEADLINE";
    String DEP_SMD_LETTER_TYPE = "DEP_SMD_LETTER_TYPE";
    String DEP_SMD_CURRENCY_ISO_CODE = "DEP_SMD_CURRENCY_ISO_CODE";
    String DEP_SMD_DEPOSIT_NUMBER = "DEP_SMD_DEPOSIT_NUMBER";
    String DEP_SMD_CUSTOMER_NUMBER = "DEP_SMD_CUSTOMER_NUMBER";
    String DEP_SMD_DEPOSIT_LIMITATION_STATE_CODE = "DEP_SMD_DEPOSIT_LIMITATION_STATE_CODE";
    String DEP_SMD_DEPOSIT_LIMITATION_STATE_VALUE = "DEP_SMD_DEPOSIT_LIMITATION_STATE_VALUE";
    String DEP_SMD_DEPOSIT_LIMITATION_TYPE_CODE = "DEP_SMD_DEPOSIT_LIMITATION_TYPE_CODE";
    String DEP_SMD_DEPOSIT_LIMITATION_TYPE_VALUE = "DEP_SMD_DEPOSIT_LIMITATION_TYPE_VALUE";
    String DEP_SMD_CREATION_DATE = "DEP_SMD_CREATION_DATE";
    String DEP_SMD_LAST_TRANSACTION_DATE = "DEP_SMD_LAST_TRANSACTION_DATE";
    String DEP_SMD_STAGNANT_DATE = "DEP_SMD_STAGNANT_DATE";
    String DEP_SMD_UNCLAIMED_DATE = "DEP_SMD_UNCLAIMED_DATE";
    String DEP_SMD_DOCUMENT_TYPE = "DEP_SMD_DOCUMENT_TYPE";
    String DEP_SMD_DEPOSIT_TYPE_NUMBER = "DEP_SMD_DEPOSIT_TYPE_NUMBER";
    String DEP_SMD_DEPOSIT_TYPE_ID = "DEP_SMD_DEPOSIT_TYPE_ID";
    String DEP_SMD_ACCOUNT_NUMBER = "DEP_SMD_ACCOUNT_NUMBER";
    String DEP_SMD_OPENING_DATE = "DEP_SMD_OPENING_DATE";
    String DEP_SMD_EXPIRE_DATE = "DEP_SMD_EXPIRE_DATE";
    String DEP_SMD_DUE_DATE = "DEP_SMD_DUE_DATE";
    String DEP_SMD_DEST_DEPOSIT_NUMBER = "DEP_SMD_DEST_DEPOSIT_NUMBER";
    String DEP_SMD_BASE_AMOUNT = "DEP_SMD_BASE_AMOUNT";
    String DEP_SMD_INTEREST_AMOUNT = "DEP_SMD_INTEREST_AMOUNT";
    String DEP_SMD_SPECIAL_INTEREST_AMOUNT = "DEP_SMD_SPECIAL_INTEREST_AMOUNT";
    String DEP_SMD_PONY_AMOUNT = "DEP_SMD_PONY_AMOUNT";
    String DEP_SMD_INTEREST_RATE = "DEP_SMD_INTEREST_RATE";
    String DEP_SMD_FROM_DATE = "DEP_SMD_FROM_DATE";
    String DEP_SMD_TO_DATE = "DEP_SMD_TO_DATE";
    String DEP_SMD_INTEREST_BASE_AMOUNT_DATE_LIST = "DEP_SMD_INTEREST_BASE_AMOUNT_DATE_LIST";
    String DEP_SMD_UPDATE_LAST_TRANSACTION_DATE = "DEP_SMD_UPDATE_LAST_TRANSACTION_DATE";
    String DEP_SMD_SKIP_DEPOSIT_TYPE_BEHAVIOR_DEBTOR_CREDITOR_VALIDATION = "DEP_SMD_SKIP_DEPOSIT_TYPE_BEHAVIOR_DEBTOR_CREDITOR_VALIDATION";
    String DEP_SMD_IGNORE_BLOCK = "DEP_SMD_IGNORE_BLOCK";
    String DEP_SMD_IGNORE_CREDITOR_BLOCK = "DEP_SMD_IGNORE_CREDITOR_BLOCK";
    String DEP_SMD_IGNORE_DEBTOR_BLOCK = "DEP_SMD_IGNORE_DEBTOR_BLOCK";
    String DEP_SMD_IGNORE_SAYAH_BIZ_CHECK = "DEP_SMD_IGNORE_SAYAH_BIZ_CHECK";
    String DEP_SMD_IGNORE_GENERATE_ACCOUNT_GROUP_LOG = "DEP_SMD_IGNORE_GENERATE_ACCOUNT_GROUP_LOG";
    String DEP_SMD_IS_FULL_CLOSE_DEPOSIT = "DEP_SMD_IS_FULL_CLOSE_DEPOSIT";
    String DEP_SMD_CLOSE_AMOUNT = "DEP_SMD_CLOSE_AMOUNT";
    String DEP_SMD_OLD_BRANCH_CODE = "DEP_SMD_OLD_BRANCH_CODE";
    String DEP_SMD_NEW_BRANCH_CODE = "DEP_SMD_NEW_BRANCH_CODE";
    String DEP_SMD_OLD_MAIN_ACCOUNT = "DEP_SMD_OLD_MAIN_ACCOUNT";
    String DEP_SMD_OLD_BLOCKED_ACCOUNT = "DEP_SMD_OLD_BLOCKED_ACCOUNT";
    String DEP_SMD_OLD_INTEREST_BLOCK_ACCOUNT = "DEP_SMD_OLD_INTEREST_BLOCK_ACCOUNT";
    String DEP_SMD_OLD_INTEREST_ACCOUNT = "DEP_SMD_OLD_INTEREST_ACCOUNT";
    String DEP_SMD_OLD_UNCLAIMED_ACCOUNT = "DEP_SMD_OLD_UNCLAIMED_ACCOUNT";
    String DEP_SMD_OLD_BANK_CLAIMS_ACCOUNT = "DEP_SMD_OLD_BANK_CLAIMS_ACCOUNT";
    String DEP_SMD_OLD_END_OF_YEAR_ACCOUNT = "DEP_SMD_OLD_END_OF_YEAR_ACCOUNT";
    String DEP_SMD_NEW_DEPOSIT_NUMBER = "DEP_SMD_NEW_DEPOSIT_NUMBER";
    String DEP_SMD_PREFERRED_INTEREST_AMOUNT = "DEP_SMD_PREFERRED_INTEREST_AMOUNT";
    String DEP_SMD_ADDED_INTEREST_AMOUNT = "DEP_SMD_ADDED_INTEREST_AMOUNT";
    String DEP_SMD_INTEREST_PENALTY_AMOUNT = "DEP_SMD_INTEREST_PENALTY_AMOUNT";
    String DEP_SMD_INTEREST_TRANSFER_DEPOSIT_TYPE_AMOUNT = "DEP_SMD_INTEREST_TRANSFER_DEPOSIT_TYPE_AMOUNT";
    String DEP_SMD_DESTINATION_INTEREST_PERCENT = "DEP_SMD_DESTINATION_INTEREST_PERCENT";
    String DEP_SMD_DESTINATION_INTEREST_NUMBER = "DEP_SMD_DESTINATION_INTEREST_NUMBER";
    String DEP_SMD_GATE_TYPE = "DEP_SMD_GATE_TYPE";
    String DEP_SMD_IGNORE_YAR_PAYMENT_BIZ_CHECK = "DEP_SMD_IGNORE_YAR_PAYMENT_BIZ_CHECK";
    String DEP_SMD_FIRST_NAME = "DEP_SMD_FIRST_NAME";
    String DEP_SMD_LAST_NAME = "DEP_SMD_LAST_NAME";
    String DEP_SMD_JIRA_TASK_NUMBER = "DEP_SMD_JIRA_TASK_NUMBER";
    String DEP_SMD_LETTER_BLOCK_OR_UNBLOCK_PASSWORD = "DEP_SMD_LETTER_BLOCK_OR_UNBLOCK_PASSWORD";
    String DEP_SMD_LETTER_CONTEXT = "DEP_SMD_LETTER_CONTEXT";
    String DEP_SMD_LETTER_DATE = "DEP_SMD_LETTER_DATE";
    String DEP_SMD_LETTER_NUMBER = "DEP_SMD_LETTER_NUMBER";
    String DEP_SMD_LETTER_RECEIPT_DATE = "DEP_SMD_LETTER_RECEIPT_DATE";
    String DEP_SMD_LETTER_TITLE = "DEP_SMD_LETTER_TITLE";
    String DEP_SMD_LETTER_CAUSE_CODE = "DEP_SMD_LETTER_CAUSE_CODE";
    String DEP_SMD_LETTER_CAUSE_VALUE = "DEP_SMD_LETTER_CAUSE_VALUE";
    String DEP_SMD_RELATED_LETTER_NUMBER = "DEP_SMD_RELATED_LETTER_NUMBER";
    String DEP_SMD_LETTER_REMAIN_AMOUNT = "DEP_SMD_LETTER_REMAIN_AMOUNT";
    String DEP_SMD_COMMISSION_TYPE_CODE = "DEP_SMD_COMMISSION_TYPE_CODE";
    String DEP_SMD_CANCEL_BLOCK_DEPOSIT_COMMISSION_DEST_DEPOSIT_NUMBERS = "DEP_SMD_CANCEL_BLOCK_DEPOSIT_COMMISSION_DEST_DEPOSIT_NUMBERS";
    String DEP_SMD_DEST_DESCRIPTION = "DEP_SMD_DEST_DESCRIPTION";
    String DEP_SMD_END_DATE = "DEP_SMD_END_DATE";
    String DEP_SMD_MANDATORY_TRANSFER = "DEP_SMD_MANDATORY_TRANSFER";
    String DEP_SMD_MIN_AMOUNT = "DEP_SMD_MIN_AMOUNT";
    String DEP_SMD_NEXT_DUE_DATE = "DEP_SMD_NEXT_DUE_DATE";
    String DEP_SMD_PERIODS_COUNT = "DEP_SMD_PERIODS_COUNT";
    String DEP_SMD_SRC_DESCRIPTION = "DEP_SMD_SRC_DESCRIPTION";
    String DEP_SMD_START_DATE = "DEP_SMD_START_DATE";
    String DEP_SMD_TRANSFER_AMOUNT = "DEP_SMD_TRANSFER_AMOUNT";
    String DEP_SMD_TRANSFER_TYPE = "DEP_SMD_TRANSFER_TYPE";
    String DEP_SMD_DAY_IN_PAYMENT_PERIOD = "DEP_SMD_DAY_IN_PAYMENT_PERIOD";
    String DEP_SMD_PAYMENT_PERIOD_LAST_DAY_IN_MONTH = "DEP_SMD_PAYMENT_PERIOD_LAST_DAY_IN_MONTH";
    String DEP_SMD_REPEAT_PAYMENT_PERIOD = "DEP_SMD_REPEAT_PAYMENT_PERIOD";
    String DEP_SMD_PAYMENT_PERIOD_REPEATABLE = "DEP_SMD_PAYMENT_PERIOD_REPEATABLE";
    String DEP_SMD_PAYMENT_PERIOD_SPECIFIED_DATE = "DEP_SMD_PAYMENT_PERIOD_SPECIFIED_DATE";
    String DEP_SMD_PAYMENT_PERIOD_REPEAT_TYPE = "DEP_SMD_PAYMENT_PERIOD_REPEAT_TYPE";
    String DEP_SMD_CLOSING_AMOUNT = "DEP_SMD_CLOSING_AMOUNT";
    String DEP_SMD_CLOSING_DATE = "DEP_SMD_CLOSING_DATE";
    String DEP_SMD_LAST_INTEREST_DATE = "DEP_SMD_LAST_INTEREST_DATE";
    String DEP_SMD_FIRST_CALCULATED_INTEREST_AMOUNT = "DEP_SMD_FIRST_CALCULATED_INTEREST_AMOUNT";
    String DEP_SMD_CALCULATION_DATE = "DEP_SMD_CALCULATION_DATE";
    String DEP_SMD_TOTAL_INTEREST_AMOUNT = "DEP_SMD_TOTAL_INTEREST_AMOUNT";
    String DEP_SMD_ON_ACCOUNT_INTEREST_ACCOUNT_NUMBER = "DEP_SMD_ON_ACCOUNT_INTEREST_ACCOUNT_NUMBER";
    String DEP_SMD_DEPOSIT_YARANE_AMOUNT = "DEP_SMD_DEPOSIT_YARANE_AMOUNT";
    String DEP_SMD_REAL_INTEREST_AMOUNT = "DEP_SMD_REAL_INTEREST_AMOUNT";
    String DEP_SMD_PAID_INTEREST_AMOUNT_TILL_LAST_PERIOD = "DEP_SMD_PAID_INTEREST_AMOUNT_TILL_LAST_PERIOD";
    String DEP_SMD_INTEREST_INFO_FOR_ORIGINAL_TYPE = "DEP_SMD_INTEREST_INFO_FOR_ORIGINAL_TYPE";
    String DEP_SMD_DEPOSIT_AMOUNT = "DEP_SMD_DEPOSIT_AMOUNT";
    String DEP_SMD_NEW_DEPOSIT_TYPE = "DEP_SMD_NEW_DEPOSIT_TYPE";
    String DEP_SMD_OLD_DEPOSIT_TYPE = "DEP_SMD_OLD_DEPOSIT_TYPE";
    String DEP_SMD_NEW_ACCOUNT_NUMBER = "DEP_SMD_NEW_ACCOUNT_NUMBER";
    String DEP_SMD_OLD_ACCOUNT_NUMBER = "DEP_SMD_OLD_ACCOUNT_NUMBER";
    String DEP_SMD_AVAILABLE_CREDIT_AMOUNT = "DEP_SMD_AVAILABLE_CREDIT_AMOUNT";
    String DEP_SMD_TRX_CHANNEL = "DEP_SMD_TRX_CHANNEL";
    String DEP_SMD_IBAN = "DEP_SMD_IBAN";
    String DEP_SMD_TRX_FIRST_NAME = "DEP_SMD_TRX_FIRST_NAME";
    String DEP_SMD_TRX_LAST_NAME = "DEP_SMD_TRX_LAST_NAME";
    String DEP_SMD_DEST_BANK_CODE = "DEP_SMD_DEST_BANK_CODE";
    String DEP_SMD_DEST_BANK_NAME = "DEP_SMD_DEST_BANK_NAME";
    String DEP_SMD_SRC_DEPOSIT_NUMBER = "DEP_SMD_SRC_DEPOSIT_NUMBER";
    String DEP_SMD_IS_CASH = "DEP_SMD_IS_CASH";
    String DEP_SMD_PORTION = "DEP_SMD_PORTION";
    String DEP_SMD_SUPPORT_DEPOSIT_NUMBER = "DEP_SMD_SUPPORT_DEPOSIT_NUMBER";
    String DEP_SMD_TRANSACTION_TYPE = "DEP_SMD_TRANSACTION_TYPE";
    String DEP_SMD_REQUEST_NATIONAL_CODE = "DEP_SMD_REQUEST_NATIONAL_CODE";
    String DEP_SMD_FIRS_NAME = "DEP_SMD_FIRS_NAME";
    String DEP_SMD_CUSTOMER_ID = "DEP_SMD_CUSTOMER_ID";
    String DEP_SMD_CTR_SERIAL = "DEP_SMD_CTR_SERIAL";
    String DEP_SMD_CAUSE_TYPE_CODE = "DEP_SMD_CAUSE_TYPE_CODE";
    String DEP_SMD_CAUSE_TYPE_VALUE = "DEP_SMD_CAUSE_TYPE_VALUE";
    String DEP_SMD_TRANSFER_MONEY_BILL = "DEP_SMD_TRANSFER_MONEY_BILL";
    String DEP_SMD_DATE = "DEP_SMD_DATE";
    String DEP_SMD_DOCUMENT_ITEM_ID = "DEP_SMD_DOCUMENT_ITEM_ID";
    String DEP_SMD_SERIAL_NUMBER = "DEP_SMD_SERIAL_NUMBER";
    String DEP_SMD_TRANSACTION_CODE = "DEP_SMD_TRANSACTION_CODE";
    String DEP_SMD_ORGANIZATION_CODE = "DEP_SMD_ORGANIZATION_CODE";
    String DEP_SMD_SPECIAL_SERVICE_ITEM = "DEP_SMD_SPECIAL_SERVICE_ITEM";
    String DEP_SMD_SPECIAL_SERVICE_ADDED_ITEM = "DEP_SMD_SPECIAL_SERVICE_ADDED_ITEM";
    String DEP_SMD_SEND_SMS_ITEM = "DEP_SMD_SEND_SMS_ITEM";
    //****************************************************

    //satna transaction
    String SATNA_TRANSACTION_SYSTEM_META_DATA_CHQ_NUMBER = "CHQ_NUMBER";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_SRC_IBAN = "SRC_IBAN";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_SRC_DEPOSIT_NUMBER = "SRC_DEPOSIT_NUMBER";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_DEST_IBAN = "DEST_IBAN";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_DEST_DEPOSIT_NUMBER = "DEST_DEPOSIT_NUMBER";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_SENDER_FULL_NAME = "SENDER_FULL_NAME";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_RECEIVER_FULL_NAME = "RECEIVER_FULL_NAME";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_DEST_BANK_CODE = "DEST_BANK_CODE";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_DEST_BANK_NAME = "DEST_BANK_NAME";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_CUSTOMER_NUMBER = "CUSTOMER_NUMBER";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_DETAIL_TYPE_ID = "DETAIL_TYPE_ID";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_DETAIL_TYPE = "DETAIL_TYPE";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_REFERENCE_NUMBER = "REFERENCE_NUMBER";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_IPADDRESS = "IPADDRESS";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_ACQ_BANK_CODE = "ACQ_BANK_CODE";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_NATIONAL_CODE = "REQUEST_NATIONAL_CODE";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_AMOUNT = "DI_AMOUNT";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_DESCRIPTION = "DESCRIPTION";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_FILE_UNIQUE_IDENTIFIER = "FILE_UNIQUE_IDENTIFIER";
    String SATNA_TRANSACTION_SYSTEM_META_DATA_FILE_UNIQUE_TRANSACTION_CHANNEL = "TRANSACTION_CHANNEL";


    //ach transaction

    String ACH_TRANSACTION_SYSTEM_META_DATA_CHQ_NUMBER = "CHQ_NUMBER";
    String ACH_TRANSACTION_SYSTEM_META_DATA_SRC_IBAN = "SRC_IBAN";
    String ACH_TRANSACTION_SYSTEM_META_DATA_SRC_DEPOSIT_NUMBER = "SRC_DEPOSIT_NUMBER";
    String ACH_TRANSACTION_SYSTEM_META_DATA_DEST_IBAN = "DEST_IBAN";
    String ACH_TRANSACTION_SYSTEM_META_DATA_DEST_DEPOSIT_NUMBER = "DEST_DEPOSIT_NUMBER";
    String ACH_TRANSACTION_SYSTEM_META_DATA_SENDER_FULL_NAME = "SENDER_FULL_NAME";
    String ACH_TRANSACTION_SYSTEM_META_DATA_RECEIVER_FULL_NAME = "RECEIVER_FULL_NAME";
    String ACH_TRANSACTION_SYSTEM_META_DATA_DEST_BANK_CODE = "DEST_BANK_CODE";
    String ACH_TRANSACTION_SYSTEM_META_DATA_DEST_BANK_NAME = "DEST_BANK_NAME";
    String ACH_TRANSACTION_SYSTEM_META_DATA_CUSTOMER_NUMBER = "CUSTOMER_NUMBER";
    String ACH_TRANSACTION_SYSTEM_META_DATA_DETAIL_TYPE_ID = "DETAIL_TYPE_ID";
    String ACH_TRANSACTION_SYSTEM_META_DATA_DETAIL_TYPE = "DETAIL_TYPE";
    String ACH_TRANSACTION_SYSTEM_META_DATA_REFERENCE_NUMBER = "REFERENCE_NUMBER";
    String ACH_TRANSACTION_SYSTEM_META_DATA_IPADDRESS = "IPADDRESS";
    String ACH_TRANSACTION_SYSTEM_META_DATA_ACQ_BANK_CODE = "ACQ_BANK_CODE";
    String ACH_TRANSACTION_SYSTEM_META_DATA_NATIONAL_CODE = "REQUEST_NATIONAL_CODE";
    String ACH_TRANSACTION_SYSTEM_META_DATA_AMOUNT = "DI_AMOUNT";
    String ACH_TRANSACTION_SYSTEM_META_DATA_DESCRIPTION = "DESCRIPTION";
    String ACH_TRANSACTION_SYSTEM_META_DATA_FILE_UNIQUE_IDENTIFIER = "FILE_UNIQUE_IDENTIFIER";
    String ACH_TRANSACTION_SYSTEM_META_DATA_FILE_UNIQUE_TRANSACTION_CHANNEL = "TRANSACTION_CHANNEL";

    String COMMISSION_DOCUMENT_ITEM_EXTRA_INFO = "COMMISSION_DOCUMENT_ITEM_EXTRA_INFO";
    String STAMP_DOCUMENT_ITEM_EXTRA_INFO = "STAMP_DOCUMENT_ITEM_EXTRA_INFO";
    String BOX_DOCUMENT_ITEM_EXTRA_INFO = "BOX_DOCUMENT_ITEM_EXTRA_INFO";
    String STAMP_DOCUMENT_ITEM_EXTRA_INFO_TYPE = "STAMP_DOCUMENT_ITEM_EXTRA_INFO_TYPE";
    String STAMP_DOCUMENT_ITEM_EXTRA_INFO_SCOPE = "STAMP_DOCUMENT_ITEM_EXTRA_INFO_SCOPE";
    String INTER_BRANCH_STAMP_DOCUMENT_ITEM_EXTRA_INFO = "INTER_BRANCH_STAMP_DOCUMENT_ITEM_EXTRA_INFO";

    // group operation system meta data DTOs
    String DEPOSIT_GROUP_OPERATION_DOCUMENT_SYSTEM_META_DATA = "DEPOSIT_GROUP_OPERATION_DOCUMENT";

    // group operation document system meta data properties
    String DEPOSIT_GROUP_OPERATION_DOCUMENT_SYSTEM_META_DATA_IDENTIFIER = "DEPOSIT_GROUP_OPERATION_DOCUMENT_IDENTIFIER";
    String DEPOSIT_GROUP_OPERATION_DOCUMENT_SYSTEM_META_DATA_SOURCE_TYPE = "DEPOSIT_GROUP_OPERATION_DOCUMENT_SOURCE_TYPE";
    String DEPOSIT_GROUP_OPERATION_DOCUMENT_SYSTEM_META_DATA_SOURCE_NUMBER = "DEPOSIT_GROUP_OPERATION_DOCUMENT_SOURCE_NUMBER";
    String DEPOSIT_GROUP_OPERATION_DOCUMENT_SYSTEM_META_DATA_DESTINATION_TYPE = "DEPOSIT_GROUP_OPERATION_DOCUMENT_DESTINATION_TYPE";
    String DEPOSIT_GROUP_OPERATION_DOCUMENT_SYSTEM_META_DATA_DESTINATION_NUMBER = "DEPOSIT_GROUP_OPERATION_DOCUMENT_DESTINATION_NUMBER";
    String DEPOSIT_GROUP_OPERATION_DOCUMENT_SYSTEM_META_DATA_AMOUNT = "DEPOSIT_GROUP_OPERATION_DOCUMENT_AMOUNT";
    String DEPOSIT_GROUP_OPERATION_DOCUMENT_SYSTEM_META_DATA_BRANCH_CODE = "DEPOSIT_GROUP_OPERATION_DOCUMENT_BRANCH_CODE";
    String DEPOSIT_TRANSACTION_TYPE_PERSIST_UPDATE_DEPOSIT_SMS_INFO_DEPOSIT_COM = "DEPOSIT_TRANSACTION_TYPE_PERSIST_UPDATE_DEPOSIT_SMS_INFO_DEPOSIT_COM";
    String DEPOSIT_SYSTEM_META_DATA_PERSIST_UPDATE_DEPOSIT_SMS_INFO_COMMISSION = "DEPOSIT_SYSTEM_META_DATA_PERSIST_UPDATE_DEPOSIT_SMS_INFO_COMMISSION";
    String DEPOSIT_TRANSACTION_TYPE_PERSIST_OPEN_DEPOSIT_SMS_INFO_DEPOSIT_COM = "DEPOSIT_TRANSACTION_TYPE_PERSIST_OPEN_DEPOSIT_SMS_INFO_DEPOSIT_COM";
    String DEPOSIT_SYSTEM_META_DATA_PERSIST_OPEN_DEPOSIT_SMS_INFO_COMMISSION = "DEPOSIT_SYSTEM_META_DATA_PERSIST_OPEN_DEPOSIT_SMS_INFO_COMMISSION";
    String USER_FIRST_NAME = "PERSONNEL_FIRST_NAME";
    String USER_LAST_NAME = "PERSONNEL_LAST_NAME";
}