package com.example.sima;

public interface SimaCodes {

    //SIMA PAGINATION
    Integer MAX_PAGE_NUMBER = 1000;
    Integer MAX_PAGE_SIZE = 10000;
    Integer MIN_PAGE_NUMBER = 1;
    Integer MIN_PAGE_SIZE = 1;


    //SIMA REQUEST TYPES
    String SIMA_REQUEST_TYPES = "SIMA_REQUEST_TYPES";
    String SIMA_SALE_SECURITIES_REQUEST_TYPE = "SIMA_SALE_SECURITIES_REQUEST_TYPE";
    String SIMA_RESALE_SECURITIES_REQUEST_TYPE = "SIMA_RESALE_SECURITIES_REQUEST_TYPE";
    String SIMA_REDEMPTION_SECURITIES_REQUEST_TYPE = "SIMA_REDEMPTION_SECURITIES_REQUEST_TYPE";
    String SIMA_TRANSFER_SECURITIES_REQUEST_TYPE = "SIMA_TRANSFER_SECURITIES_REQUEST_TYPE";
    String SIMA_REVERSE_CONTRACT_REQUEST_TYPE = "SIMA_REVERSE_CONTRACT_REQUEST_TYPE";
    String SIMA_UNBLOCK_CUSTOMER_REQUEST_TYPE = "SIMA_UNBLOCK_CUSTOMER_REQUEST_TYPE";
    String SIMA_BLOCK_CUSTOMER_REQUEST_TYPE = "SIMA_BLOCK_CUSTOMER_REQUEST_TYPE";
    String SIMA_ALLOCATED_SECURITIES_REQUEST_TYPE = "SIMA_ALLOCATED_SECURITIES_REQUEST_TYPE";
    String SIMA_ALLOCATED_SECURITIES_CODES_REQUEST_TYPE = "SIMA_ALLOCATED_SECURITIES_CODES_REQUEST_TYPE";
    String SIMA_SECURITIES_CODE_FOR_SAlE_REQUEST_TYPE = "SIMA_SECURITIES_CODE_FOR_SAlE_REQUEST_TYPE";
    String SIMA_SECURITIES_CODE_FOR_RESAlE_REQUEST_TYPE = "SIMA_SECURITIES_CODE_FOR_RESAlE_REQUEST_TYPE";
    String SIMA_SECURITIES_CODE_FOR_REDEMPTION_REQUEST_TYPE = "SIMA_SECURITIES_CODE_FOR_REDEMPTION_REQUEST_TYPE";
    String SIMA_SECURITIES_CODE_FOR_TRANSFER_REQUEST_TYPE = "SIMA_SECURITIES_CODE_FOR_TRANSFER_REQUEST_TYPE";
    String SIMA_SECURITIES_FOR_SALE_REQUEST_TYPE = "SIMA_SECURITIES_FOR_SALE_REQUEST_TYPE";
    String SIMA_SECURITIES_FOR_RESALE_REQUEST_TYPE = "SIMA_SECURITIES_FOR_RESALE_REQUEST_TYPE";
    String SIMA_SECURITIES_FOR_TRANSFER_REQUEST_TYPE = "SIMA_SECURITIES_FOR_TRANSFER_REQUEST_TYPE";
    String SIMA_SECURITIES_FOR_REDEMPTION_REQUEST_TYPE = "SIMA_SECURITIES_FOR_REDEMPTION_REQUEST_TYPE";
    String SIMA_SALE_INTEREST_FOR_ONE_SECURITIES_REQUEST_TYPE = "SIMA_SALE_INTEREST_FOR_ONE_SECURITIES_REQUEST_TYPE";
    String SIMA_REDEMPTION_INTEREST_REQUEST_TYPE = "SIMA_REDEMPTION_INTEREST_REQUEST_TYPE";
    String SIMA_RESALE_INTEREST_FOR_ONE_SECURITIES_REQUEST_TYPE = "SIMA_RESALE_INTEREST_FOR_ONE_SECURITIES_REQUEST_TYPE";
    String SIMA_CREATE_PERSON_REQUEST_TYPE = "SIMA_CREATE_PERSON_REQUEST_TYPE";
    String SIMA_UPDATE_PERSON_REQUEST_TYPE = "SIMA_UPDATE_PERSON_REQUEST_TYPE";
    String SIMA_GET_PERSON_REQUEST_TYPE = "SIMA_GET_PERSON_REQUEST_TYPE";
    String SIMA_CREATE_ORGANIZATION_REQUEST_TYPE = "SIMA_CREATE_ORGANIZATION_REQUEST_TYPE";
    String SIMA_UPDATE_ORGANIZATION_REQUEST_TYPE = "SIMA_UPDATE_ORGANIZATION_REQUEST_TYPE";
    String SIMA_IS_PARTY_BLOCKED_REQUEST_TYPE = "SIMA_IS_PARTY_BLOCKED_REQUEST_TYPE";
    String SIMA_GET_ORGANIZATION_REQUEST_TYPE = "SIMA_GET_ORGANIZATION_REQUEST_TYPE";
    String SIMA_PING_REQUEST_TYPE = "SIMA_PING_REQUEST_TYPE";
    String SIMA_GET_SIMA_SECURITIES_COUPONS_DATE_REQUEST_TYPE = "SIMA_GET_SIMA_SECURITIES_COUPONS_DATE_REQUEST_TYPE";
    String SIMA_PARTIAL_BLOCK_ACCOUNT_REQUEST_TYPE = "SIMA_PARTIAL_BLOCK_ACCOUNT_REQUEST_TYPE";
    String SIMA_BLOCK_ACCOUNT_REQUEST_TYPE = "SIMA_BLOCK_ACCOUNT_REQUEST_TYPE";
    String SIMA_UNBLOCK_ACCOUNT_REQUEST_TYPE = "SIMA_UNBLOCK_ACCOUNT_REQUEST_TYPE";
    String SIMA_UPDATE_CUSTOMER_IBAN_REQUEST_TYPE = "SIMA_UPDATE_CUSTOMER_IBAN_REQUEST_TYPE";
    String SIMA_PARTIAL_UNBLOCK_ACCOUNT_REQUEST_TYPE = "SIMA_PARTIAL_UNBLOCK_ACCOUNT_REQUEST_TYPE";
    String SIMA_GET_ACCOUNT_REQUEST_TYPE = "SIMA_GET_ACCOUNT_REQUEST_TYPE";
    String SIMA_UPDATE_AGENT_IBAN_REQUEST_TYPE = "SIMA_UPDATE_AGENT_IBAN_REQUEST_TYPE";

    //SIMA REQUEST STATUS
    String SIMA_REQUEST_STATUS = "SIMA_REQUEST_STATUS";
    String SIMA_REQUEST_SENT_STATUS = "SIMA_REQUEST_SENT_STATUS";
    String SIMA_REQUEST_REGISTERED_STATUS = "SIMA_REQUEST_REGISTERED_STATUS";
    String SIMA_REQUEST_ERROR_ON_SEND_STATUS = "SIMA_REQUEST_NOT_SEND_STATUS";
    String SIMA_REQUEST_HAS_RESPONSE_STATUS = "SIMA_REQUEST_HAS_RESPONSE_STATUS";
    String SIMA_REQUEST_WAIT_FOR_SEND_STATUS = "SIMA_REQUEST_WAIT_FOR_SEND_STATUS";

    //CUSTOMER STATUS
    String SIMA_CUSTOMER_STATUS = "SIMA_CUSTOMER_STATUS";
    String SIMA_CUSTOMER_BLOCK_STATUS = "SIMA_CUSTOMER_BLOCK_STATUS";
    String SIMA_CUSTOMER_ACTIVE_STATUS = "SIMA_CUSTOMER_ACTIVE_STATUS";
    String SIMA_CUSTOMER_WAITING_FOR_RESPONSE_STATUS = "SIMA_CUSTOMER_WAITING_FOR_RESPONSE_STATUS";
    String SIMA_CUSTOMER_UNSUCCESSFUL_REGISTERED_STATUS = "SIMA_CUSTOMER_UNSUCCESSFUL_REGISTERED_STATUS";

    //SIMA CUSTOMER IDENTIFIER TYPE
    String SIMA_CUSTOMER_IDENTIFIER_TYPE = "SIMA_CUSTOMER_IDENTIFIER_TYPE";
    String SIMA_CUSTOMER_NATIONAL_CODE_TYPE = "SIMA_CUSTOMER_NATIONAL_CODE_TYPE";
    String SIMA_CUSTOMER_IDENTIFIER_CODE_TYPE = "SIMA_CUSTOMER_IDENTIFIER_CODE_TYPE";
    String SIMA_FOREIGN_CUSTOMER_NATIONAL_CODE_TYPE = "SIMA_FOREIGN_CUSTOMER_NATIONAL_CODE_TYPE";


    //SIMA REQUEST OPERATION TYPE
    String SIMA_REQUEST_OPERATION_TYPE = "SIMA_REQUEST_OPERATION_TYPE";
    String SIMA_SEND_REQUEST_OPERATION_TYPE = "SIMA_SEND_REQUEST_OPERATION_TYPE";
    String SIMA_FAILED_SEND_REQUEST_OPERATION_TYPE = "SIMA_FAILED_SEND_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_GET_ALLOCATED_SECURITIES_REQUEST_OPERATION_TYPE = "SEND_SIMA_GET_ALLOCATED_SECURITIES_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_GET_SIMA_SECURITIES_COUPONS_DATE_REQUEST_OPERATION_TYPE = "SEND_SIMA_GET_SIMA_SECURITIES_COUPONS_DATE_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_SECURITIES_FOR_SAlE_REQUEST_OPERATION_TYPE = "SEND_SIMA_SECURITIES_FOR_SAlE_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_SECURITIES_FOR_RESAlE_REQUEST_OPERATION_TYPE = "SEND_SIMA_SECURITIES_FOR_RESAlE_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_SECURITIES_FOR_TRANSFER_REQUEST_OPERATION_TYPE = "SEND_SIMA_SECURITIES_FOR_TRANSFER_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_SECURITIES_FOR_REDEMPTION_REQUEST_OPERATION_TYPE = "SEND_SIMA_SECURITIES_FOR_REDEMPTION_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_SALE_INTEREST_FOR_ONE_SECURITIES_REQUEST_OPERATION_TYPE = "SEND_SIMA_SALE_INTEREST_FOR_ONE_SECURITIES_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_REDEMPTION_INTEREST_FOR_ONE_SECURITIES_REQUEST_OPERATION_TYPE = "SEND_SIMA_REDEMPTION_INTEREST_FOR_ONE_SECURITIES_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_RESALE_INTEREST_FOR_ONE_SECURITIES_REQUEST_OPERATION_TYPE = "SEND_SIMA_RESALE_INTEREST_FOR_ONE_SECURITIES_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_SALE_SECURITIES_REQUEST_OPERATION_TYPE = "SEND_SIMA_SALE_SECURITIES_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_RESALE_SECURITIES_REQUEST_OPERATION_TYPE = "SEND_SIMA_RESALE_SECURITIES_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_TRANSFER_SECURITIES_REQUEST_OPERATION_TYPE = "SEND_SIMA_TRANSFER_SECURITIES_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_REDEMPTION_REQUEST_OPERATION_TYPE = "SEND_SIMA_REDEMPTION_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_PARTIAL_BLOCK_ACCOUNT_REQUEST_OPERATION_TYPE = "SEND_SIMA_PARTIAL_BLOCK_ACCOUNT_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_GET_ACCOUNT_REQUEST_OPERATION_TYPE = "SEND_SIMA_GET_ACCOUNT_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_CREATE_PERSON_REQUEST_OPERATION_TYPE = "SEND_SIMA_CREATE_PERSON_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_CREATE_CUSTOMER_REQUEST_OPERATION_TYPE = "SEND_SIMA_CREATE_CUSTOMER_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_CREATE_ORGANIZATION_REQUEST_OPERATION_TYPE = "SEND_SIMA_CREATE_ORGANIZATION_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_UPDATE_PERSON_REQUEST_OPERATION_TYPE = "SEND_SIMA_UPDATE_PERSON_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_UPDATE_ORGANIZATION_REQUEST_OPERATION_TYPE = "SEND_SIMA_UPDATE_ORGANIZATION_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_GET_PERSON_REQUEST_OPERATION_TYPE = "SEND_SIMA_GET_PERSON_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_GET_ORGANIZATION_REQUEST_OPERATION_TYPE = "SEND_SIMA_GET_ORGANIZATION_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_BLOCK_CUSTOMER_REQUEST_OPERATION_TYPE = "SEND_SIMA_BLOCK_CUSTOMER_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_UNBLOCK_CUSTOMER_REQUEST_OPERATION_TYPE = "SEND_SIMA_UNBLOCK_CUSTOMER_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_IS_PARTY_BLOCKED_REQUEST_OPERATION_TYPE = "SEND_SIMA_IS_PARTY_BLOCKED_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_PING_REQUEST_OPERATION_TYPE = "SEND_SIMA_PING_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_BLOCK_ACCOUNT_REQUEST_OPERATION_TYPE = "SEND_SIMA_BLOCK_ACCOUNT_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_UNBLOCK_ACCOUNT_REQUEST_OPERATION_TYPE = "SEND_SIMA_UNBLOCK_ACCOUNT_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_UPDATE_CUSTOMER_IBAN_REQUEST_OPERATION_TYPE = "SEND_SIMA_UPDATE_CUSTOMER_IBAN_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_PARTIAL_UNBLOCK_ACCOUNT_REQUEST_OPERATION_TYPE = "SEND_SIMA_PARTIAL_UNBLOCK_ACCOUNT_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_UPDATE_AGENT_IBAN_REQUEST_OPERATION_TYPE = "SEND_SIMA_UPDATE_AGENT_IBAN_REQUEST_OPERATION_TYPE";
    String SEND_SIMA_REVERSE_CONTRACT_REQUEST_OPERATION_TYPE = "SEND_SIMA_REVERSE_CONTRACT_REQUEST_OPERATION_TYPE";


    //SIMA RESPONSE OPERATION TYPE
    String SIMA_RESPONSE_OPERATION_TYPE = "SIMA_RESPONSE_OPERATION_TYPE";
    String SIMA_RECEIVED_RESPONSE_OPERATION_TYPE = "SIMA_RECEIVED_RESPONSE_OPERATION_TYPE";
    String ADD_ALLOCATED_SIMA_SECURITIES_RESPONSE_OPERATION_TYPE = "ADD_ALLOCATED_SIMA_SECURITIES_RESPONSE_OPERATION_TYPE";
    String FILL_ALLOCATED_SIMA_SECURITIES_RESPONSE_OPERATION_TYPE = "FILL_ALLOCATED_SIMA_SECURITIES_RESPONSE_OPERATION_TYPE";
    String UPDATE_ALLOCATED_SIMA_SECURITIES_STATUS_RESPONSE_OPERATION_TYPE = "UPDATE_ALLOCATED_SIMA_SECURITIES_STATUS_RESPONSE_OPERATION_TYPE";
    String UPDATE_ALLOCATED_SIMA_SECURITIES_DAILY_INTEREST_AMOUNT_RESPONSE_OPERATION_TYPE = "UPDATE_ALLOCATED_SIMA_SECURITIES_DAILY_INTEREST_AMOUNT_RESPONSE_OPERATION_TYPE";
    String UPDATE_SIMA_SECURITIES_INTEREST_INFO_OPERATION_TYPE = "UPDATE_SIMA_SECURITIES_INTEREST_INFO_OPERATION_TYPE";
    String UPDATE_SIMA_CUSTOMER_LAST_RESPONSE_OPERATION_TYPE = "UPDATE_SIMA_CUSTOMER_LAST_RESPONSE_OPERATION_TYPE";
    String UPDATE_SIMA_SECURITIES_LAST_RESPONSE_OPERATION_TYPE = "UPDATE_SIMA_SECURITIES_LAST_RESPONSE_OPERATION_TYPE";
    String UPDATE_SIMA_CONTRACT_LAST_RESPONSE_OPERATION_TYPE = "UPDATE_SIMA_CONTRACT_LAST_RESPONSE_OPERATION_TYPE";
    String UPDATE_SIMA_ACCOUNT_LAST_RESPONSE_OPERATION_TYPE = "UPDATE_SIMA_ACCOUNT_LAST_RESPONSE_OPERATION_TYPE";
    String SIMA_SALES_SECURITIES_CODES_RESPONSE_OPERATION_TYPE = "SIMA_SALES_SECURITIES_CODES_RESPONSE_OPERATION_TYPE";
    String SIMA_RESALE_SECURITIES_CODES_RESPONSE_OPERATION_TYPE = "SIMA_RESALE_SECURITIES_CODES_RESPONSE_OPERATION_TYPE";
    String SIMA_REDEMPTION_INTEREST_AMOUNT_RESPONSE_OPERATION_TYPE = "SIMA_REDEMPTION_INTEREST_AMOUNT_RESPONSE_OPERATION_TYPE";
    String SIMA_RESALE_INTEREST_AMOUNT_RESPONSE_OPERATION_TYPE = "SIMA_RESALE_INTEREST_AMOUNT_RESPONSE_OPERATION_TYPE";
    String SIMA_REDEMPTION_PENALTY_AMOUNT_RESPONSE_OPERATION_TYPE = "SIMA_REDEMPTION_PENALTY_AMOUNT_RESPONSE_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_STATUS_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_STATUS_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_ACCOUNT_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_ACCOUNT_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_AMOUNT_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_AMOUNT_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_INTEREST_AMOUNT_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_INTEREST_AMOUNT_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_TRANSACTION_ID_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_TRANSACTION_ID_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_BRANCH_DETAIL_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_BRANCH_DETAIL_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_TRANSACTION_CODE_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_TRANSACTION_CODE_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_REVERSE_TRANSACTION_NUMBER_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_REVERSE_TRANSACTION_NUMBER_OPERATION_TYPE";
    String UPDATE_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE = "UPDATE_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE";
    String ADD_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE = "ADD_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE";
    String ADD_SIMA_SALE_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE = "ADD_SIMA_SALE_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE";
    String ADD_SIMA_TRANSFER_FROM_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE = "ADD_SIMA_TRANSFER_FROM_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE";
    String ADD_SIMA_TRANSFER_TO_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE = "ADD_SIMA_TRANSFER_TO_FROM_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE";
    String ADD_SIMA_RESALE_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE = "ADD_SIMA_RESALE_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE";
    String ADD_SIMA_REDEMPTION_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE = "ADD_SIMA_REDEMPTION_CONTRACT_ON_SIMA_ACCOUNT_RESPONSE_OPERATION_TYPE";
    String SIMA_REDEMPTION_SECURITIES_CODES_RESPONSE_OPERATION_TYPE = "SIMA_REDEMPTION_SECURITIES_CODES_RESPONSE_OPERATION_TYPE";
    String SIMA_TRANSFER_SECURITIES_CODES_RESPONSE_OPERATION_TYPE = "SIMA_TRANSFER_SECURITIES_CODES_RESPONSE_OPERATION_TYPE";
    String SIMA_SECURITIES_RECEIVED_COUPONS_DATE_OPERATION_TYPE = "SIMA_SECURITIES_RECEIVED_COUPONS_DATE_OPERATION_TYPE";
    String SIMA_SECURITIES_RECEIVED_SALE_INTEREST_RESPONSE_OPERATION_TYPE = "SIMA_SECURITIES_RECEIVED_SALE_INTEREST_RESPONSE_OPERATION_TYPE";
    String SIMA_SECURITIES_RECEIVED_SECURITIES_FOR_SALE_RESPONSE_OPERATION_TYPE = "SIMA_SECURITIES_RECEIVED_SECURITIES_FOR_SALE_RESPONSE_OPERATION_TYPE";
    String UPDATE_SIMA_CUSTOMER_RESPONSE_OPERATION_TYPE = "UPDATE_SIMA_CUSTOMER_RESPONSE_OPERATION_TYPE";
    String UPDATE_SIMA_CONTRACT_IBAN_OPERATION_TYPE = "UPDATE_SIMA_CONTRACT_IBAN_OPERATION_TYPE";
    String UPDATE_SIMA_CUSTOMER_STATUS_RESPONSE_OPERATION_TYPE = "UPDATE_SIMA_CUSTOMER_STATUS_RESPONSE_OPERATION_TYPE";
    String UPDATE_SIMA_SECURITIES_PRINCIPAL_IBAN_OPERATION_TYPE = "UPDATE_SIMA_SECURITIES_PRINCIPAL_IBAN_OPERATION_TYPE";
    String UPDATE_SIMA_SECURITIES_INTEREST_IBAN_OPERATION_TYPE = "UPDATE_SIMA_SECURITIES_INTEREST_IBAN_OPERATION_TYPE";
    String SIMA_CHANGE_CONTRACT_TRANSACTION_NUMBER_OPERATION_TYPE = "SIMA_CHANGE_CONTRACT_TRANSACTION_NUMBER_OPERATION_TYPE";

    // SIMA MACRO OPERATION TYPE
    String SIMA_MACRO_OPERATION_TYPE = "SIMA_MACRO_OPERATION_TYPE";
    String DEPOSIT_INTEREST_MACRO_OPERATION_TYPE = "DEPOSIT_INTEREST_MACRO_OPERATION_TYPE";
    String DEPOSIT_PRINCIPAL_MACRO_OPERATION_TYPE = "DEPOSIT_PRINCIPAL_MACRO_OPERATION_TYPE";

    //SIMA JMS RESPONSE OPERATION TYPE
    String SIMA_JMS_RESPONSE_OPERATION_TYPE = "SIMA_JMS_RESPONSE_OPERATION_TYPE";
    String SIMA_JMS_PROCESSED_RESPONSE_OPERATION_TYPE = "SIMA_JMS_PROCESSED_RESPONSE_OPERATION_TYPE";
    String SIMA_JMS_NOT_PROCESSED_RESPONSE_OPERATION_TYPE = "SIMA_JMS_NOT_PROCESSED_RESPONSE_OPERATION_TYPE";

    //SIMA CUSTOMER OPERATION TYPE
    String SIMA_CUSTOMER_OPERATION_TYPE = "SIMA_CUSTOMER_OPERATION_TYPE";
    String SIMA_REGISTER_CUSTOMER_OPERATION_TYPE = "SIMA_REGISTER_CUSTOMER_OPERATION_TYPE";
    String SIMA_UNBLOCK_CUSTOMER_OPERATION_TYPE = "SIMA_UNBLOCK_CUSTOMER_OPERATION_TYPE";
    String SIMA_BLOCK_CUSTOMER_OPERATION_TYPE = "SIMA_BLOCK_CUSTOMER_OPERATION_TYPE";

    //SIMA_SEQUENCE_CODE
    String SIMA_SEQUENCE_CODE = "SIMA_SEQUENCE_CODE";

    //SIMA RESPONSE STATUS (AckCodeType)
    String SIMA_RESPONSE_SUCCESS_ACK = "SUCCESS";
    String SIMA_RESPONSE_WARNING_ACK = "WARNING";
    String SIMA_RESPONSE_FAILURE_ACK = "FAILURE";

    String SIMA_RESPONSE_ACK_TYPE = "SIMA_RESPONSE_ACK_TYPE";

    //SIMA SECURITIES FEATURE
    String SIMA_SECURITIES_FEATURE = "SIMA_SECURITIES_FEATURE";
    String SIMA_SELLING_START_DATE = "SIMA_SELLING_START_DATE";
    String SIMA_SELLING_END_DATE = "SIMA_SELLING_END_DATE";
    String SIMA_SECURITIES_DURATION = "SIMA_SECURITIES_DURATION";
    String SIMA_INTEREST_PAYMENT_INTERVAL = "SIMA_INTEREST_PAYMENT_INTERVAL";
    String SIMA_COUPON_RATE = "SIMA_COUPON_RATE";
    String SIMA_REDEMPTION_RATE = "SIMA_REDEMPTION_RATE";
    String SIMA_PAR_VALUE = "SIMA_PAR_VALUE";
    String SIMA_NON_REDEEMABLE = "SIMA_NON_REDEEMABLE";
    String SIMA_NON_TRANSFERABLE = "SIMA_NON_TRANSFERABLE";
    String SIMA_FINAL_RATE_OF_RETURN = "SIMA_FINAL_RATE_OF_RETURN";
    String SIMA_BOND_TYPE = "SIMA_BOND_TYPE";
    String SIMA_ISSUE_SUBJECT = "SIMA_ISSUE_SUBJECT";
    String SIMA_GUARANTOR = "SIMA_GUARANTOR";
    String SIMA_TRUSTEE = "SIMA_TRUSTEE";
    String SIMA_OBLIGOR = "SIMA_OBLIGOR";
    String SIMA_ISSUER = "SIMA_ISSUER";

    //SIMA SECURITIES TYPE STATUS
    String SIMA_SECURITIES_STATUS = "SIMA_SECURITIES_STATUS";
    String SIMA_SECURITIES_ACTIVE_STATUS = "SIMA_SECURITIES_ACTIVE_STATUS";
    String SIMA_SECURITIES_INACTIVE_STATUS = "SIMA_SECURITIES_INACTIVE_STATUS";
    String SIMA_SECURITIES_MATURED_STATUS = "SIMA_SECURITIES_MATURED_STATUS";

    //SIMA REQUEST LOG
    String SIMA_REQUEST_LOG_TYPE = "SIMA_REQUEST_LOG_TYPE";

    String SIMA_SECURITIES_TYPE_PREFIX_STATUS = "SIMA_SECURITIES_TYPE_";
    String SIMA_SECURITIES_TYPE_POSTFIX_STATUS = "_STATUS";
    String SIMA_SECURITIES_TYPE_FEATURE_TYPE_PREFIX = "SIMA_";


    String SIMA_REGISTER_LOG_OPERATION = "SIMA_REGISTER_LOG_OPERATION";
    String SIMA_RECEIVE_RESPONSE_OPERATION = "SIMA_RECEIVE_RESPONSE_OPERATION";
    String SIMA_SEND_REQUEST_OPERATION = "SIMA_SEND_REQUEST_OPERATION";
    String SIMA_PROCESS_RESPONSE_OPERATION = "SIMA_PROCESS_RESPONSE_OPERATION";
    String SIMA_PROCESS_AND_PARS_JMS_REQUEST_OPERATION = "SIMA_PROCESS_AND_PARS_JMS_REQUEST_OPERATION";
    String SIMA_ISSUE_DOCUMENT_OPERATION = "SIMA_ISSUE_DOCUMENT_OPERATION";
    String SIMA_ISSUE_DOCUMENT_AGAIN = "صدور مجدد سند";
    String ASSIGN_SIMA_SECURITIES_INTEREST_INFO = "افزودن اطلاعات سرفصل ها/سپرده اوراق سیما";
    String LOAD_ASSIGNED_INTEREST_INFO = "نمایش اطلاعات سرفصل ها/سپرده اوراق سیما";

    String MAX_RESULT_FOR_PROCESS_MQ_REQUEST = "MAX_RESULT_FOR_PROCESS_MQ_REQUEST";
    String SIMA_SECURITIES_ACCOUNT_TYPE = "SIMA_SECURITIES_ACCOUNT_TYPE";
    String SIMA_ACTIVE_SECURITIES_ACCOUNT = "SIMA_ACTIVE_SECURITIES_ACCOUNT";
    String SIMA_BLOCKED_SECURITIES_ACCOUNT = "SIMA_BLOCKED_SECURITIES_ACCOUNT";
    String SIMA_MATURED_SECURITIES_ACCOUNT = "SIMA_MATURED_SECURITIES_ACCOUNT";
    String SIMA_CLOSED_SECURITIES_ACCOUNT = "SIMA_CLOSED_SECURITIES_ACCOUNT";
    String SIMA_WAIT_FOR_BLOCK_RESPONSE_ACCOUNT = "SIMA_WAIT_FOR_BLOCK_RESPONSE_ACCOUNT";
    String SIMA_WAIT_FOR_UNBLOCK_RESPONSE_ACCOUNT = "SIMA_WAIT_FOR_UNBLOCK_RESPONSE_ACCOUNT";
    String SIMA_PARTIAL_BLOCKED_SECURITIES_ACCOUNT = "SIMA_PARTIAL_BLOCKED_SECURITIES_ACCOUNT";

    //SIMA RESPONSE ERROR TYPE
    String SIMA_RESPONSE_ERROR_TYPES = "SIMA_RESPONSE_ERROR_TYPES";

    //SIMA CUSTOMER CHANGED FIELD
    String SIMA_CUSTOMER_CHANGED_FIELD = "SIMA_CUSTOMER_CHANGED_FIELD";
    String SIMA_CUSTOMER_STATUS_CHANGED_FIELD = "SIMA_CUSTOMER_STATUS_CHANGED_FIELD";

    //SIMA CONTRACT STATUS
    String SIMA_CONTRACT_STATUS = "SIMA_CONTRACT_STATUS";
    String SIMA_CONTRACT_REGISTERED = "SIMA_CONTRACT_REGISTERED";
    String SIMA_CONTRACT_REQUEST_SENT = "SIMA_CONTRACT_REQUEST_SENT";
    String SIMA_CONTRACT_FAILED_REQUEST = "SIMA_CONTRACT_FAILED_REQUEST";
    String SIMA_CONTRACT_COMPLETED = "SIMA_CONTRACT_COMPLETED";
    String SIMA_CONTRACT_DID_NOT_COMPLETED = "SIMA_CONTRACT_DID_NOT_COMPLETED";
    String SIMA_CONTRACT_TERMINATED = "SIMA_CONTRACT_TERMINATED";
    String SIMA_CONTRACT_CANCELED = "SIMA_CONTRACT_CANCELED";
    String SIMA_CONTRACT_FAILED_ISSUE_DOCUMENT = "SIMA_CONTRACT_FAILED_ISSUE_DOCUMENT";
    String SIMA_CONTRACT_CANCELED_FAILED_ISSUE_DOCUMENT = "SIMA_CONTRACT_CANCELED_FAILED_ISSUE_DOCUMENT";

    //SIMA CONTRACT OPERATION TYPE
    String SIMA_CONTRACT_OPERATION_TYPE = "SIMA_CONTRACT_OPERATION_TYPE";
    String SIMA_REGISTER_CONTRACT_OPERATION_TYPE = "SIMA_REGISTER_CONTRACT_OPERATION_TYPE";

    //SIMA ACCOUNT OPERATION TYPE
    String SIMA_ACCOUNT_OPERATION_TYPE = "SIMA_ACCOUNT_OPERATION_TYPE";
    String SIMA_CHANGE_ACCOUNT_STATUS_OPERATION_TYPE = "SIMA_CHANGE_ACCOUNT_STATUS_OPERATION_TYPE";
    String SIMA_CHANGE_ACCOUNT_AVAILABLE_BALANCE_OPERATION_TYPE = "SIMA_CHANGE_ACCOUNT_AVAILABLE_BALANCE_OPERATION_TYPE";
    String SIMA_CHANGE_ACCOUNT_BLOCK_BALANCE_OPERATION_TYPE = "SIMA_CHANGE_ACCOUNT_BLOCK_BALANCE_OPERATION_TYPE";
    String SIMA_CHANGE_ACCOUNT_TOTAL_BALANCE_OPERATION_TYPE = "SIMA_CHANGE_ACCOUNT_TOTAL_BALANCE_OPERATION_TYPE";

    String SIMA_SECURITIES_CHANGED_FIELD = "SIMA_SECURITIES_CHANGED_FIELD";
    String SIMA_SECURITIES_SALABLE_CHANGED_FIELD = "SIMA_SECURITIES_SALABLE_CHANGED_FIELD";
    String SIMA_SECURITIES_REDEEMABLE_CHANGED_FIELD = "SIMA_SECURITIES_REDEEMABLE_CHANGED_FIELD";
    String SIMA_SECURITIES_RESALABLE_BY_AGENT_CHANGED_FIELD = "SIMA_SECURITIES_RESALABLE_BY_AGENT_CHANGED_FIELD";
    String SIMA_SECURITIES_RESALABLE_BY_PUBLISHER_CHANGED_FIELD = "SIMA_SECURITIES_RESALABLE_BY_PUBLISHER_CHANGED_FIELD";
    String SIMA_SECURITIES_RESALE_AVAILABLE_BALANCE_BY_AGENT_CHANGED_FIELD = "SIMA_SECURITIES_RESALE_AVAILABLE_BALANCE_BY_AGENT_CHANGED_FIELD";
    String SIMA_SECURITIES_RESALE_AVAILABLE_BALANCE_BY_PUBLISHER_CHANGED_FIELD = "SIMA_SECURITIES_RESALE_AVAILABLE_BALANCE_BY_PUBLISHER_CHANGED_FIELD";
    String SIMA_SECURITIES_TRANSFERABLE_CHANGED_FIELD = "SIMA_SECURITIES_TRANSFERABLE_CHANGED_FIELD";
    String SIMA_SECURITIES_COUPONS_DATE_CHANGED_FIELD = "SIMA_SECURITIES_COUPONS_DATE_CHANGED_FIELD";
    String SIMA_SECURITIES_INTEREST_AMOUNT_CHANGED_FIELD = "SIMA_SECURITIES_INTEREST_AMOUNT_CHANGED_FIELD";
    String SIMA_SECURITIES_DAILY_INTEREST_AMOUNT_CHANGED_FIELD = "SIMA_SECURITIES_DAILY_INTEREST_AMOUNT_CHANGED_FIELD";
    String SIMA_SECURITIES_IS_SPECIAL_CHANGED_FIELD = "SIMA_SECURITIES_IS_SPECIAL_CHANGED_FIELD";
    String SIMA_SECURITIES_DEPOSIT_ID_CHANGED_FIELD = "SIMA_SECURITIES_DEPOSIT_ID_CHANGED_FIELD";
    String SIMA_SECURITIES_CREDITOR_TOPIC_CHANGED_FIELD = "SIMA_SECURITIES_CREDITOR_TOPIC_CHANGED_FIELD";
    String SIMA_SECURITIES_DEBTOR_TOPIC_CHANGED_FIELD = "SIMA_SECURITIES_DEBTOR_TOPIC_CHANGED_FIELD";
    String SIMA_SECURITIES_SALE_AVAILABLE_BALANCE_CHANGED_FIELD = "SIMA_SECURITIES_SALE_AVAILABLE_BALANCE_CHANGED_FIELD";
    String SIMA_SECURITIES_PRINCIPAL_IBAN_CHANGED_FIELD = "SIMA_SECURITIES_PRINCIPAL_IBAN_CHANGED_FIELD";
    String SIMA_SECURITIES_INTEREST_IBAN_CHANGED_FIELD = "SIMA_SECURITIES_INTEREST_IBAN_CHANGED_FIELD";


    String SIMA_CONTRACT_ACTION_TYPE = "SIMA_CONTRACT_ACTION_TYPE";
    String SIMA_SALE_CONTRACT_ACTION_TYPE = "SIMA_SALE_CONTRACT_ACTION_TYPE";
    String SIMA_RESALE_CONTRACT_ACTION_TYPE = "SIMA_RESALE_CONTRACT_ACTION_TYPE";
    String SIMA_REDEMPTION_CONTRACT_ACTION_TYPE = "SIMA_REDEMPTION_CONTRACT_ACTION_TYPE";
    String SIMA_TRANSFER_CONTRACT_ACTION_TYPE = "SIMA_TRANSFER_CONTRACT_ACTION_TYPE";

    String SIMA_CONTRACT_CHANGED_FIELD = "SIMA_CONTRACT_CHANGED_FIELD";
    String SIMA_CONTRACT_REDEMPTION_INTEREST_AMOUNT_CHANGED_FIELD = "SIMA_CONTRACT_REDEMPTION_INTEREST_AMOUNT_CHANGED_FIELD";
    String SIMA_CONTRACT_RESALE_INTEREST_AMOUNT_CHANGED_FIELD = "SIMA_CONTRACT_RESALE_INTEREST_AMOUNT_CHANGED_FIELD";
    String SIMA_CONTRACT_REDEMPTION_PENALTY_AMOUNT_CHANGED_FIELD = "SIMA_CONTRACT_REDEMPTION_PENALTY_AMOUNT_CHANGED_FIELD";
    String SIMA_CONTRACT_STATUS_CHANGED_FIELD = "SIMA_CONTRACT_STATUS_CHANGED_FIELD";
    String SIMA_CONTRACT_ACCOUNT_CHANGED_FIELD = "SIMA_CONTRACT_ACCOUNT_CHANGED_FIELD";
    String SIMA_CONTRACT_AMOUNT_CHANGED_FIELD = "SIMA_CONTRACT_AMOUNT_CHANGED_FIELD";
    String SIMA_CONTRACT_INTEREST_AMOUNT_CHANGED_FIELD = "SIMA_CONTRACT_INTEREST_AMOUNT_CHANGED_FIELD";
    String SIMA_CONTRACT_TRANSACTION_ID_CHANGED_FIELD = "SIMA_CONTRACT_TRANSACTION_ID_CHANGED_FIELD";
    String SIMA_CONTRACT_IBAN_CHANGED_FIELD = "SIMA_CONTRACT_IBAN_CHANGED_FIELD";
    String SIMA_CONTRACT_BRANCH_DETAIL_CHANGED_FIELD = "SIMA_CONTRACT_BRANCH_DETAIL_CHANGED_FIELD";
    String SIMA_CONTRACT_TRANSACTION_CODE_CHANGED_FIELD = "SIMA_CONTRACT_TRANSACTION_CODE_CHANGED_FIELD";
    String SIMA_CONTRACT_REVERSE_TRANSACTION_NUMBER_CHANGED_FIELD = "SIMA_CONTRACT_REVERSE_TRANSACTION_NUMBER_CHANGED_FIELD";
    String SIMA_CONTRACT_TRANSACTION_NUMBER_CHANGED_FIELD = "SIMA_CONTRACT_TRANSACTION_NUMBER_CHANGED_FIELD";

    String SIMA_INTEREST_PAYMENT_INTERVAL_UNIT = "SIMA_INTEREST_PAYMENT_INTERVAL_UNIT";
    String SIMA_MONTHLY_INTEREST_PAYMENT = "SIMA_MONTHLY_INTEREST_PAYMENT";
    String SIMA_YEARLY_INTEREST_PAYMENT = "SIMA_YEARLY_INTEREST_PAYMENT";
    String YEAR = "YEAR";
    String MONTH = "MONTH";
    String DAY = "DAY";

    String SIMA_ACCOUNT_CHANGED_FIELD = "SIMA_ACCOUNT_CHANGED_FIELD";
    String SIMA_ACCOUNT_STATUS_CHANGED_FIELD = "SIMA_ACCOUNT_STATUS_CHANGED_FIELD";
    String SIMA_ACCOUNT_AVAILABLE_BALANCE_CHANGED_FIELD = "SIMA_ACCOUNT_AVAILABLE_BALANCE_CHANGED_FIELD";
    String SIMA_ACCOUNT_BLOCK_BALANCE_CHANGED_FIELD = "SIMA_ACCOUNT_BLOCK_BALANCE_CHANGED_FIELD";
    String SIMA_ACCOUNT_TOTAL_BALANCE_CHANGED_FIELD = "SIMA_ACCOUNT_TOTAL_BALANCE_CHANGED_FIELD";
    String SIMA_BLOCK_OR_UNBLOCK_ACCOUNT_TYPES = "SIMA_BLOCK_OR_UNBLOCK_ACCOUNT_TYPES";
    String SIMA_PARTIAL_BLOCK_ACCOUNT_TYPE = "SIMA_PARTIAL_BLOCK_ACCOUNT_TYPE";
    String SIMA_TOTAL_BLOCK_ACCOUNT_TYPE = "SIMA_TOTAL_BLOCK_ACCOUNT_TYPE";
    String SIMA_TOTAL_UNBLOCK_ACCOUNT_TYPE = "SIMA_TOTAL_UNBLOCK_ACCOUNT_TYPE";
    String SIMA_PARTIAL_UNBLOCK_ACCOUNT_TYPE = "SIMA_PARTIAL_UNBLOCK_ACCOUNT_TYPE";


    String ADD_SIMA_SALE_CONTRACT_OPERATION_TYPE = "ADD_SIMA_SALE_CONTRACT_OPERATION_TYPE";
    String SIMA_SALE_CONTRACT_RECEIVE_RESPONSE_OPERATION_TYPE = "SIMA_SALE_CONTRACT_RECEIVE_RESPONSE_OPERATION_TYPE";
    String SIMA_RESALE_CONTRACT_RECEIVE_RESPONSE_OPERATION_TYPE = "SIMA_RESALE_CONTRACT_RECEIVE_RESPONSE_OPERATION_TYPE";
    String ADD_SIMA_RESALE_CONTRACT_OPERATION_TYPE = "ADD_SIMA_RESALE_CONTRACT_OPERATION_TYPE";

    //SIMA IBAN TYPE
    String SIMA_IBAN_TYPE = "SIMA_IBAN_TYPE";
    String SIMA_PRINCIPAL_IBAN_TYPE = "SIMA_PRINCIPAL_IBAN_TYPE";
    String SIMA_INTEREST_IBAN_TYPE = "SIMA_INTEREST_IBAN_TYPE";

    //SIMA TRADING SOURCE TYPE
    String SIMA_TRADING_SOURCE_TYPE = "SIMA_TRADING_SOURCE_TYPE";
    String PUBLISHER_TRADING_SOURCE = "PUBLISHER_TRADING_SOURCE";
    String AGENT_TRADING_SOURCE = "AGENT_TRADING_SOURCE";


    //SIMA MACRO
    String MACRO_UPDATE_RESALE_AND_REDEMPTION_INTEREST_CONTRACT = "MACRO_UPDATE_RESALE_AND_REDEMPTION_INTEREST_CONTRACT";
    String IS_SIMA_ACTIVE = "IS_SIMA_ACTIVE";
    String BLOCK_PASSWORD = "BLOCK_PASSWORD";
    String UNBLOCK_PASSWORD = "UNBLOCK_PASSWORD";
    String MACRO_FIX_CONFLICT_OF_SIMA_SALE_TRANSACTIONS = "receive-daily-report-of-sima-sale-contract";
    String MACRO_FIX_CONFLICT_OF_SIMA_RESALE_TRANSACTIONS = "receive-daily-report-of-sima-resale-contract";
    String MACRO_FIX_CONFLICT_OF_SIMA_TRANSFER_TRANSACTIONS = "receive-daily-report-of-sima-transfer-contract";
    String MACRO_FIX_CONFLICT_OF_SIMA_REDEMPTION_TRANSACTIONS = "receive-daily-report-of-sima-redemption-contract";
    String MACRO_FIX_CONFLICT_OF_SIMA_REVERSE_TRANSACTIONS = "receive-daily-report-of-sima-reverse-contract";
    String MACRO_FIX_CONFLICT_OF_SIMA_BLOCK_ACCOUNTS = "receive-daily-report-of-sima-block-account";
    String MACRO_DEPOSIT_SIMA_INTEREST_PRINCIPAL = "deposit-sima-interest";

    //SIMA CSV FILE REPORT TYPE
    String BLOCK = "block";
    String REDEMPTION = "redemption";
    String RESALE = "resale";
    String REVERSE = "reverse";
    String SALE = "sale";
    String TRANSFER = "transfer";

    //SIMA CCTI FILE TYPE
    String INTEREST = "interest";
    String PRINCIPAL = "principal";

    // sima transaction types
    String SIMA_TR_TY_SALE_SIMA_SECURITIES = "SIMA_TR_TY_SALE_SIMA_SECURITIES";
    String SIMA_TR_TY_RESALE_SIMA_SECURITIES = "SIMA_TR_TY_RESALE_SIMA_SECURITIES";
    String SIMA_TR_TY_REDEMPTION_SIMA_SECURITIES = "SIMA_TR_TY_REDEMPTION_SIMA_SECURITIES";
    String SIMA_TR_TY_TRANSFER_SIMA_SECURITIES = "SIMA_TR_TY_TRANSFER_SIMA_SECURITIES";
    String SIMA_TR_TY_REVERSE_SALE_SIMA_SECURITIES = "SIMA_TR_TY_REVERSE_SALE_SIMA_SECURITIES";
    String SIMA_TR_TY_REVERSE_RESALE_SIMA_SECURITIES = "SIMA_TR_TY_REVERSE_RESALE_SIMA_SECURITIES";
    String SIMA_TR_TY_REVERSE_REDEMPTION_SIMA_SECURITIES = "SIMA_TR_TY_REVERSE_REDEMPTION_SIMA_SECURITIES";
    String SIMA_TR_TY_REVERSE_TRANSFER_SIMA_SECURITIES = "SIMA_TR_TY_REVERSE_TRANSFER_SIMA_SECURITIES";
    String SIMA_TR_TY_DEPOSIT_SIMA_PRINCIPAL = "SIMA_TR_TY_DEPOSIT_SIMA_PRINCIPAL";
    String SIMA_TR_TY_DEPOSIT_SIMA_INTEREST = "SIMA_TR_TY_DEPOSIT_SIMA_INTEREST";

    // document descriptions
    String SALE_DOCUMENT_COMMENT = "سند فروش اوراق به مشتری سیما ";
    String RESALE_DOCUMENT_COMMENT = "سند باز فروش اوراق به مشتری سیما ";
    String REDEMPTION_DOCUMENT_COMMENT = "سند بازخرید اوراق به مشتری سیما ";
    String TRANSFER_DOCUMENT_COMMENT = "سند انتقال اوراق به مشتری سیما ";
    String REVERSE_SALE_DOCUMENT_COMMENT = "سند لغو فروش اوراق به مشتری سیما ";
    String REVERSE_RESALE_DOCUMENT_COMMENT = "سند لغو باز فروش اوراق به مشتری سیما ";
    String REVERSE_REDEMPTION_DOCUMENT_COMMENT = "سند لغو بازخرید اوراق به مشتری سیما ";
    String REVERSE_TRANSFER_DOCUMENT_COMMENT = "سند لغو انتقال اوراق به مشتری سیما ";

    String USER_NAME = "USER_NAME";
    String PASSWORD = "PASSWORD";
    String BRANCH_CODE = "BRANCH_CODE";
    String REQUEST_QUEUE_NAME = "REQUEST_QUEUE_NAME";
    String VERSION = "VERSION";

    // SIMA DEPOSIT INTEREST STATUS
    String SIMA_DEPOSIT_INTEREST_STATUS = "SIMA_DEPOSIT_INTEREST_STATUS";
    String SIMA_DEPOSIT_INTEREST_SUCCESSFUL_STATUS = "SIMA_DEPOSIT_INTEREST_SUCCESSFUL_STATUS";
    String SIMA_DEPOSIT_INTEREST_FAILED_STATUS = "SIMA_DEPOSIT_INTEREST_FAILED_STATUS";
    String SIMA_DEPOSIT_INTEREST_IN_PROGRESS_STATUS = "SIMA_DEPOSIT_INTEREST_IN_PROGRESS_STATUS";

    // SIMA DAILY REPORT CONFLICT FIXING MACRO STATUS
    String DAILY_REPORT_MACRO_STATUS = "DAILY_REPORT_MACRO_STATUS";
    String CONFLICT_FOUND_IN_DAILY_REPORT_MACRO_STATUS = "CONFLICT_FOUND_IN_DAILY_REPORT_MACRO_STATUS";
    String CONFLICT_NOT_FOUND_IN_DAILY_REPORT_MACRO_STATUS = "CONFLICT_NOT_FOUND_IN_DAILY_REPORT_MACRO_STATUS";
    String ERROR_IN_FIXING_CONFLICT_IN_DAILY_REPORT_MACRO_STATUS = "ERROR_IN_FIXING_CONFLICT_IN_DAILY_REPORT_MACRO_STATUS";

    // SIMA REPORT FILE TYPE FROM CENTRAL BANK

    String SIMA_REPORT_FILE_TYPE = "SIMA_REPORT_FILE_TYPE";
    String TRANSFER_REPORT = "TRANSFER_REPORT";
    String SALE_REPORT = "SALE_REPORT";
    String RESALE_REPORT = "RESALE_REPORT";
    String INTEREST_REPORT = "INTEREST_REPORT";
    String BLOCK_REPORT = "BLOCK_REPORT";
    String PRINCIPAL_REPORT = "PRINCIPAL_REPORT";
    String REVERSE_REPORT = "REVERSE_REPORT";
    String REDEMPTION_REPORT = "REDEMPTION_REPORT";
    String COUPON_INTEREST_REPORT = "COUPON_INTEREST_REPORT";

    //SIMA system meta data
    String SIMA_SYSTEM_META_DATA = "SIMA_SYSTEM_META_DATA";
    String SIMA_SYSTEM_META_DATA_SIMA_ACCOUNT_ID = "SIMA_SYSTEM_META_DATA_SIMA_ACCOUNT_ID";
    String SIMA_SYSTEM_META_DATA_SIMA_CONTRACT_ID = "SIMA_SYSTEM_META_DATA_SIMA_CONTRACT_ID";
    String SIMA_SYSTEM_META_DATA_BUYER_SIMA_ACCOUNT_ID = "SIMA_SYSTEM_META_DATA_BUYER_SIMA_ACCOUNT_ID";
    String SIMA_SYSTEM_META_DATA_BUYER_CREDITOR_ACCOUNT_NUMBER = "SIMA_SYSTEM_META_DATA_BUYER_CREDITOR_ACCOUNT_NUMBER";
    String FILE_RESULT_TYPE = "FILE_RESULT_TYPE";
    String NOT_RECEIVED_FAILED_SIMA_RESPONSE = "NOT_RECEIVED_FAILED_SIMA_RESPONSE";
    String MQ_REQUEST_NOT_PROCEED = "MQ_REQUEST_NOT_PROCEED";
    String MQ_REQUEST_PROCEED = "MQ_REQUEST_PROCEED";
    String MQ_REQUEST_INVALID_FORMAT = "MQ_REQUEST_INVALID_FORMAT";
    String MQ_REQUEST_STATUS = "MQ_REQUEST_STATUS";
}

